"""Aviation Maintenance Academy - Wave 6 content pack.
Adds 5 new modules balanced across tracks. Merged in academy_data.py.
"""

EXT11_MODULES = [
  {
    "id": "corrosion_control", "title": "Corrosion Identification & Control", "track": "general", "icon": "&#x1F6E1;",
    "sections": [
      {"heading": "Types of Corrosion", "body": "<b>Uniform surface corrosion</b> etches evenly across a surface; <b>pitting corrosion</b> creates small localized pits, often under coatings; <b>galvanic corrosion</b> occurs when two dissimilar metals contact in the presence of an electrolyte (e.g., moisture); <b>intergranular corrosion</b> attacks grain boundaries inside the metal, often invisible from the surface until advanced."},
      {"heading": "Causes & Contributing Factors", "body": "Moisture, salt air, battery acid spills, and trapped dirt/debris all accelerate corrosion. Poor drainage, damaged paint/primer, and dissimilar-metal fastener combinations (without proper isolation) create ideal conditions. Aircraft operated near coastal or industrial areas face elevated corrosion risk and often need more frequent inspection."},
      {"heading": "Detection & Treatment", "body": "Corrosion is found via visual inspection (sometimes with magnification), and confirmed/assessed via NDI methods for hidden or advanced cases. Treatment involves mechanical removal (sanding/blasting) down to sound metal, chemical conversion coating, and reapplication of primer/paint - the specific process and allowable removal limits are per the structural repair manual (SRM)."},
      {"heading": "Prevention", "body": "Preventive measures include regular washing (especially after coastal/salt exposure), maintaining paint/primer integrity, using corrosion-inhibiting compounds (CIC) in fay surfaces and unpressurized bays, and ensuring drain holes remain clear. Dissimilar metals are isolated with sealant, primer, or non-conductive barriers to prevent galvanic action."},
      {"heading": "Corrosion Prevention Program Elements", "body": "An effective corrosion prevention and control program (CPCP) combines scheduled zonal inspections targeting known moisture-trap areas, application/reapplication of corrosion-preventive compounds (CPC) on a defined interval, and prompt repair of any paint/finish damage before it allows moisture ingress. Environmental factors (coastal/high-humidity basing, deicing fluid exposure) drive shorter CPC reapplication intervals for some operators. Any corrosion finding is documented, measured against SRM allowable limits, and tracked to closure - repeat findings in the same area trigger a root-cause review rather than just another blend-out."},
      {"heading": "Zonal Inspection Program Design", "body": "A well-designed corrosion prevention program divides the aircraft into inspection zones based on corrosion susceptibility (galley/lavatory areas, wheel wells, battery compartments rated higher risk than dry, sheltered interior structure) and assigns inspection intervals accordingly - high-risk zones get more frequent, more detailed inspection than low-risk zones, rather than applying one uniform interval across the whole aircraft. This risk-based zonal approach concentrates inspection resources where corrosion is statistically most likely to develop, catching problems earlier in the highest-risk areas without wasting inspection effort on consistently dry, low-risk structure."}
    , {"heading": "Corrosion Control in Fuel Tank Areas", "body": "Integral fuel tanks (wet-wing structures) are particularly susceptible to corrosion from water contamination that settles at the tank bottom and low points, since water promotes both general corrosion and microbial growth that produces corrosive byproducts. Fuel tank sealant deterioration can allow water intrusion at structural joints, and sump drains must be checked and drained regularly to remove accumulated water before it causes corrosion damage to tank structure. Corrosion inspection inside fuel tanks requires confined-space entry procedures with proper vapor testing and ventilation, and any corrosion found on tank structure must be evaluated against structural repair manual limits since fuel tank structure is often primary load-bearing structure."}, {"heading": "Galvanic Corrosion and Dissimilar Metal Contact", "body": "Galvanic corrosion occurs when two dissimilar metals with different electrochemical potentials are in electrical contact in the presence of an electrolyte (such as moisture), causing the more anodic (less noble) metal to corrode preferentially while the more cathodic (more noble) metal is protected. Aircraft structures frequently combine different metals, such as aluminum skins with steel or titanium fasteners, making galvanic corrosion a persistent concern that is managed through isolation techniques like anodizing, primer coatings, sealants, and non-conductive isolators (washers, sleeves, or gaskets) placed between dissimilar metal interfaces. The galvanic series ranks metals by their relative nobility, and understanding this ranking helps mechanics predict which metal in a dissimilar pair will corrode and select appropriate isolation or sacrificial protection methods. When performing repairs, using the correct fastener material specified by the maintenance manual is critical, since substituting an incompatible fastener material can introduce galvanic corrosion that was not present in the original design."},
    {"heading": "Corrosion Control in Wheel Wells and Landing Gear Bays", "body": "Wheel wells and landing gear bays are among the most corrosion-prone zones on an aircraft due to constant exposure to runway de-icing chemicals, moisture, mud, tire rubber debris, and hydraulic fluid residue, combined with the presence of dissimilar metals (steel gear components, aluminum structure, cadmium or other plated fasteners) in close proximity. Corrosion control programs specify frequent wash/rinse cycles for these zones, particularly after operations in areas using deicing chemicals, along with inspection for coating breakdown on gear legs and bay structure where mud and debris accumulation can trap moisture against the surface for extended periods. Because landing gear components carry high static and dynamic loads, corrosion pitting on a highly loaded gear leg or attachment fitting is far more structurally significant than similar pitting on lightly loaded skin, so wheel well corrosion findings often require more conservative blend-out limits or engineering disposition compared to equivalent corrosion elsewhere on the airframe."},
    {"heading": "Corrosion Control in Empennage and Control Surface Hinge Areas", "body": "Empennage structures and control surface hinge points are particularly susceptible to corrosion because they combine several risk factors: dissimilar metal contact at hinge fittings and bearings, water collection points at low structural areas and drain paths that can become blocked, and limited air circulation in enclosed rib bays that allows condensation to persist rather than evaporate. Hinge bearings and bushings, often made of different material than the surrounding structure for wear resistance, require periodic lubrication per the maintenance manual not only for mechanical function but also to displace moisture and provide a barrier against corrosion at the metal-to-metal interface; a hinge that receives inadequate or infrequent lubrication is at elevated risk for both wear and corrosion-related binding. Drain holes and paths in empennage structure must be verified clear during routine inspection, since a blocked drain allows water to pool inside the structure rather than exiting, leading to internal corrosion that may not be visible from external inspection alone. Technicians inspecting empennage areas should pay particular attention to areas where dissimilar metals meet at fasteners or fittings, and should treat any corrosion found at a hinge point with particular urgency given the flight-critical nature of control surface hinge integrity."}],
    "quiz": [ {"q": "In a galvanic corrosion couple between two dissimilar metals, which metal corrodes preferentially?", "choices": ["The metal with the higher electrical resistance", "The more anodic (less noble) metal in the galvanic series", "Always the metal that is physically larger", "Neither metal is affected without an electrolyte present, regardless of contact"], "answer": 1}, {"q": "Why are integral fuel tanks particularly susceptible to corrosion?", "choices": ["Fuel itself directly causes corrosion", "Water contamination settling at tank low points promotes corrosion and microbial growth", "Fuel tanks are never inspected", "Aluminum does not corrode near fuel"], "answer": 1, "explain": "Water that settles at the bottom of fuel tanks promotes corrosion and microbial growth, making regular sump draining and inspection critical."},
      {"q": "Why does a corrosion prevention program typically assign different inspection intervals to different aircraft zones rather than one uniform interval?", "choices": ["Uniform intervals are always better", "Different zones have different corrosion risk levels, so a risk-based approach concentrates inspection where it matters most", "Zonal programs are purely bureaucratic with no technical basis", "All aircraft areas have identical corrosion risk"], "answer": 1, "explain": "A risk-based zonal approach assigns more frequent, detailed inspection to high-corrosion-risk areas (like wheel wells and lavatories) and less frequent inspection to low-risk dry areas, using inspection resources more effectively."},
      {"q": "Why might an aircraft based in a coastal, high-humidity environment need a shorter corrosion-preventive compound (CPC) reapplication interval?", "choices": ["Coastal environments have no effect on corrosion risk", "Higher moisture/salt exposure accelerates corrosion, requiring more frequent CPC reapplication", "It only affects paint color", "CPC intervals never change"], "answer": 1, "explain": "Coastal/high-humidity environments accelerate corrosion, so CPC programs are often tailored with shorter reapplication intervals for aircraft based there."},
      {"q": "What is galvanic corrosion caused by?", "choices": ["UV light exposure","Two dissimilar metals in contact with an electrolyte","Extreme cold","Excess lubrication"], "answer": 1, "explain": "Galvanic corrosion results from contact between dissimilar metals in the presence of an electrolyte like moisture."},
      {"q": "Which corrosion type attacks grain boundaries and can be invisible from the surface?", "choices": ["Uniform surface corrosion","Pitting corrosion","Intergranular corrosion","Filiform corrosion"], "answer": 2, "explain": "Intergranular corrosion progresses along internal grain boundaries and may not be visible until advanced."},
      {"q": "What document specifies allowable corrosion removal limits?", "choices": ["The pilot's operating handbook","The structural repair manual (SRM)","The weight and balance report","The MEL"], "answer": 1, "explain": "The SRM defines approved corrosion removal procedures and allowable material loss limits."},
      {"q": "How are dissimilar metals typically isolated to prevent galvanic corrosion?", "choices": ["They are never joined","Sealant, primer, or non-conductive barriers between them","Painting only the exterior","Using thicker fasteners"], "answer": 1, "explain": "Isolating dissimilar metals with sealant, primer, or barriers prevents the electrolytic path needed for galvanic corrosion."},
      {"q": "Why do coastal-based aircraft often need more frequent corrosion inspection?", "choices": ["They fly higher","Salt air significantly accelerates corrosion","They are heavier","They use different fuel"], "answer": 1, "explain": "Salt-laden coastal air is a major corrosion accelerant, warranting more frequent inspection in those environments."},
    {"q": "Why does corrosion pitting on a landing gear leg typically warrant more conservative treatment than similar pitting on lightly loaded skin panels?", "choices": ["Landing gear components are not subject to corrosion", "Gear components carry high static and dynamic loads, so corrosion pitting there is more structurally significant than on lightly loaded skin", "Gear legs are always replaced rather than repaired regardless of corrosion severity", "Corrosion severity is judged identically regardless of the component's structural loading"], "answer": 1},
    {"q": "Why are control surface hinge areas particularly susceptible to corrosion?", "choices": ["Hinges are never exposed to moisture", "They combine dissimilar metal contact, water collection points, and limited air circulation that allows condensation to persist", "Corrosion cannot occur on moving parts", "Hinges are always made of corrosion-proof materials"], "answer": 1}
    ]
  },
  {
    "id": "hydraulic_systems", "title": "Hydraulic Power Systems", "track": "airframe", "icon": "&#x1F4A7;",
    "sections": [
      {"heading": "Basic Hydraulic Principles", "body": "Hydraulic systems use <b>Pascal's Law</b> (pressure applied to a confined fluid transmits equally in all directions) to multiply force through pistons of different areas. Components include a reservoir, pump(s) (engine-driven, electric, or manual), pressure regulator/relief valve, actuators, and selector/control valves."},
      {"heading": "System Components", "body": "An <b>accumulator</b> stores pressurized fluid (using a gas-charged piston or bladder) to dampen pressure spikes and provide backup pressure. <b>Filters</b> remove contamination that can damage seals and valves. <b>Check valves</b> allow flow in one direction only; <b>relief valves</b> protect against overpressure."},
      {"heading": "Open vs. Closed Center Systems", "body": "In an <b>open-center</b> system, fluid circulates continuously through the system at low pressure when no actuator is being commanded. In a <b>closed-center</b> system, the pump maintains a static pressure with valves closed until an actuator is commanded, then flow is directed on demand - closed-center systems are common on larger transport aircraft with multiple simultaneous users."},
      {"heading": "Maintenance & Troubleshooting", "body": "Common issues include internal/external leaks, contaminated fluid, air in the system (causing sponginess/erratic operation), and worn seals. Hydraulic fluid type (e.g., MIL-H-5606 mineral-based vs. Skydrol phosphate-ester) must never be mixed - incompatible fluids can destroy seals. Fluid level, cleanliness, and system pressure are checked per the AMM."},
      {"heading": "Hydraulic Contamination Control", "body": "Hydraulic fluid contamination (particulate, water, or air) is a leading cause of component wear and erratic operation - filters with differential-pressure indicators (popped button/bypass indicator) signal a filter nearing capacity and should be changed before it bypasses unfiltered fluid into the system. Fluid should be sampled and particle-counted per program requirements, and any system opened for maintenance must be capped/bagged immediately to prevent contamination ingress. Mixing incompatible fluid types (e.g., mineral-based vs. phosphate-ester/skydrol) causes seal swelling and failure - always verify fluid type before servicing."},
      {"heading": "System Bleeding and Air Removal", "body": "Air trapped in a hydraulic system causes spongy, delayed, or inconsistent actuator response since air compresses under pressure while hydraulic fluid does not - a system that was opened for component replacement must be properly bled per the AMM procedure (often cycling the actuator through its full range multiple times at a bleed point) to fully purge trapped air before the system is considered airworthy. A system that seems to work but responds sluggishly or requires multiple actuations to achieve full travel often still has residual trapped air requiring further bleeding."}
    , {"heading": "Hydraulic Pump Types and Failure Signatures", "body": "Aircraft hydraulic systems use various pump designs including engine-driven variable-displacement piston pumps (most common on transport aircraft, automatically adjusting output to maintain system pressure under varying demand), fixed-displacement pumps paired with a pressure relief valve, and electric motor-driven pumps for auxiliary or backup power. Variable-displacement pump failure often first manifests as pressure fluctuation or slow pressure buildup rather than complete pressure loss, since internal wear allows some but not all of the pump's designed output capacity to be lost. Case drain flow monitoring on variable-displacement pumps provides an early indicator of internal wear, since excessive case drain flow indicates internal leakage past pump components before the pump fails to maintain system pressure entirely."},
    {"heading": "Hydraulic Fluid Types and Cross-Contamination Hazards", "body": "Aircraft hydraulic systems use fluids that are not interchangeable: mineral-based fluid (MIL-H-5606, red), phosphate-ester fluid (Skydrol/Hyjet, purple, fire-resistant), and some military systems still use MIL-PRF-87257. Phosphate-ester fluid aggressively attacks the seals, paint, and elastomers formulated for mineral-based systems, and mineral-based fluid contaminating a phosphate-ester system causes seal swelling and rapid seal failure; even trace cross-contamination from a shared service cart, funnel, or improperly cleaned reservoir can degrade an entire system. Because the two fluid families look different in color but can still be mistaken under poor lighting or in small residual quantities, servicing equipment (carts, hoses, funnels) must be dedicated to a single fluid type and clearly labeled, and any suspected cross-contamination event requires fluid sampling and analysis before the aircraft is released to service."},
    {"heading": "Hydraulic Reservoir Pressurization and Level Indication", "body": "Many aircraft hydraulic reservoirs are pressurized (using bleed air or a system-generated pressure signal) above ambient to ensure a positive supply pressure at the pump inlet, preventing pump cavitation particularly at altitude where ambient pressure is low, or during maneuvers that could otherwise cause the reservoir to unport if only gravity-fed. Reservoir level indication, whether a sight gauge, float-type quantity sensor, or electronic level sensor, must be checked with the system in the correct configuration specified by the AMM (often with gear/flaps in a specific position and system depressurized or at a specific pressure) since hydraulic fluid volume in the reservoir varies with actuator positions throughout the system; checking level in the wrong configuration gives a reading that appears normal but does not reflect true fluid quantity. A reservoir level that reads normal does not by itself confirm every downstream component is receiving adequate flow: a component internally bypassing fluid to a low-pressure return line can starve other actuators of adequate flow or pressure even while total reservoir quantity, and therefore its level indication, remains unchanged, which is an important nuance when troubleshooting a system performance complaint with no corresponding low-reservoir indication."},
    {"heading": "Hydraulic System Pressure Testing and Proof Pressure Verification", "body": "Hydraulic system pressure testing verifies that lines, fittings, components, and structure can safely withstand operating pressure with adequate margin, and is performed after component replacement, major repair, or per scheduled maintenance intervals specified in the maintenance manual. Proof pressure testing applies a pressure above normal operating pressure (typically 1.5 times operating pressure, per the applicable specification) for a specified duration to verify the system withstands this elevated pressure without leakage, permanent deformation, or failure, providing a safety margin beyond normal operating conditions; proof testing is distinct from and less severe than burst testing, which deliberately tests to failure and is performed only on sample components during design qualification, never on installed aircraft systems. During a system pressure test, technicians must verify all fittings, quick-disconnects, and joints are properly torqued and free of visible leakage at test pressure, and must follow the specified pressurization rate, avoiding rapid pressure spikes that could cause a false failure indication or genuine damage, and dwell time. Any leakage detected during proof pressure testing must be corrected and the affected joint or component retested before the aircraft is returned to service, since a joint that leaks at proof pressure, even if it does not leak at normal operating pressure, indicates inadequate margin that could develop into an in-service leak."}],
    "quiz": [ {"q": "What symptom pattern typically indicates a variable-displacement piston pump's pressure compensator is failing rather than the pump being completely seized?", "choices": ["Complete loss of all hydraulic flow with no pump rotation", "Erratic pressure fluctuations or inability to maintain steady pressure under load, even though the pump still turns and produces some flow", "Immediate catastrophic pump destruction", "No detectable symptoms of any kind"], "answer": 1}, {"q": "What does excessive case drain flow on a variable-displacement hydraulic pump typically indicate?", "choices": ["Normal operation with no concern", "Internal leakage past pump components, an early indicator of wear", "The pump is producing maximum rated output", "A fault in the pressure relief valve only"], "answer": 1, "explain": "Excessive case drain flow indicates internal leakage within the pump, serving as an early warning sign of wear before complete pressure loss occurs."},
      {"q": "Why does trapped air in a hydraulic system cause spongy or delayed actuator response?", "choices": ["Air has no effect on hydraulic system performance", "Air compresses under pressure while hydraulic fluid does not, causing inconsistent force transmission", "Air makes the fluid flow faster", "Trapped air only affects fluid color"], "answer": 1, "explain": "Unlike hydraulic fluid, air is compressible, so trapped air absorbs pressure changes instead of transmitting them consistently, causing spongy or delayed actuator response."},
      {"q": "Mixing an incompatible hydraulic fluid type into a system (e.g., mineral-based fluid into a phosphate-ester system) typically causes:", "choices": ["Improved performance", "Seal swelling and failure due to chemical incompatibility", "No effect at all", "Faster response time"], "answer": 1, "explain": "Incompatible hydraulic fluid chemistries cause seals designed for one fluid type to swell, degrade, and fail when exposed to the wrong fluid."},
      {"q": "What principle allows hydraulic systems to multiply force?", "choices": ["Bernoulli's principle","Pascal's Law","Newton's third law","Boyle's Law"], "answer": 1, "explain": "Pascal's Law states that pressure applied to a confined fluid is transmitted equally, allowing force multiplication through different piston areas."},
      {"q": "What is the purpose of a hydraulic accumulator?", "choices": ["To filter fluid","To store pressurized fluid, dampening spikes and providing backup pressure","To cool the fluid","To measure flow rate"], "answer": 1, "explain": "An accumulator stores pressurized fluid via a gas-charged piston/bladder for shock dampening and backup pressure."},
      {"q": "In a closed-center hydraulic system, what happens when no actuator is commanded?", "choices": ["Fluid circulates continuously at low pressure","The pump maintains static pressure with valves closed until needed","The pump shuts off completely","Fluid drains to the reservoir"], "answer": 1, "explain": "Closed-center systems hold static pressure with valves closed, directing flow on demand when an actuator is commanded."},
      {"q": "Why must hydraulic fluid types never be mixed?", "choices": ["It changes the fluid color","Incompatible fluids (e.g., mineral-based vs. phosphate-ester) can destroy seals","It has no real effect","It only affects fluid cost"], "answer": 1, "explain": "Mixing incompatible hydraulic fluid types can cause seal swelling/deterioration and system failure."},
      {"q": "What symptom often indicates air trapped in a hydraulic system?", "choices": ["Perfectly smooth operation","Sponginess or erratic actuator operation","Increased fluid temperature only","Louder pump noise only"], "answer": 1, "explain": "Air in hydraulic fluid compresses, causing spongy or erratic actuator response instead of firm, consistent movement."},
    {"q": "Why must hydraulic servicing carts and funnels be dedicated to a single fluid type rather than shared between mineral-based and phosphate-ester systems?", "choices": ["Shared equipment is more expensive to maintain", "Cross-contamination between the two fluid families causes seal swelling and rapid seal failure", "The two fluid types have identical chemical properties so sharing is fine", "Regulatory paperwork requires separate carts regardless of compatibility"], "answer": 1},
    {"q": "Why must hydraulic reservoir fluid level be checked with the aircraft in the specific configuration (gear/flap position, system pressure) specified by the maintenance manual?", "choices": ["Configuration has no effect on reservoir level readings", "Reservoir fluid volume varies with actuator positions throughout the system, so checking in the wrong configuration gives a misleading reading", "Reservoir level can only be checked while the aircraft is in flight", "The maintenance manual configuration requirement is arbitrary and for convenience only"], "answer": 1},
    {"q": "What is the purpose of hydraulic system proof pressure testing?", "choices": ["To deliberately test the system to failure", "To verify the system withstands pressure above normal operating pressure without leakage or damage, confirming adequate safety margin", "To reduce system operating pressure permanently", "Proof testing is only performed during initial aircraft manufacture, never during maintenance"], "answer": 1}
    ]
  },
  {
    "id": "landing_gear_systems", "title": "Landing Gear Systems", "track": "airframe", "icon": "&#x1F6EC;",
    "sections": [
      {"heading": "Gear Configurations", "body": "<b>Tricycle</b> gear (nose + two main) is most common on modern aircraft, offering good ground handling and visibility. <b>Tailwheel (conventional)</b> gear places two main wheels forward of the CG and a small tailwheel aft - more prone to ground-looping but preferred for rough-field operation on some aircraft."},
      {"heading": "Retraction Systems", "body": "Retractable gear uses hydraulic, electric, or pneumatic actuators to raise/lower gear, with mechanical uplocks/downlocks to secure position. Emergency extension systems (free-fall, backup hydraulic, or manual crank) allow gear extension if the primary system fails. Position indicators (lights, mechanical pins) confirm gear is safely down and locked before landing."},
      {"heading": "Shock Struts (Oleo)", "body": "Most gear uses an <b>oleo-pneumatic strut</b> combining compressed air/nitrogen (springing action) with hydraulic fluid (damping) to absorb landing and taxi shock loads. Proper strut extension (checked against a chart, often via visible exposed chrome/piston length) indicates correct servicing - under- or over-serviced struts affect ground handling and shock absorption."},
      {"heading": "Brakes & Tires", "body": "Most aircraft use <b>disc brakes</b> (single or multiple-disc) actuated hydraulically; some large aircraft have <b>anti-skid</b> systems that modulate brake pressure to prevent tire skidding, maximizing braking efficiency. Tire condition (tread wear, cuts, proper inflation) is critical - underinflated tires overheat and can fail; correct inflation is checked cold per the tire chart."},
      {"heading": "Retraction System Troubleshooting", "body": "A gear that fails to retract or extend fully often traces to a hydraulic actuator seal leak (reducing available pressure/flow), a sequence valve out of adjustment (causing doors/gear to bind against each other), or a position switch/microswitch misaligned so the system doesn't receive the 'gear down and locked' or 'gear up' confirmation signal even though the gear physically reached position. Always verify squat switch and position indicator rigging per the AMM before condemning a hydraulic component, since electrical/rigging issues frequently masquerade as hydraulic failures."},
      {"heading": "Shock Strut Servicing", "body": "Oleo-pneumatic shock struts require both correct fluid level and correct nitrogen charge pressure - servicing one without the other produces an incorrectly performing strut even if the extended strut height looks approximately correct. Too little nitrogen charge results in a strut that bottoms out harshly on landing; too much fluid with insufficient air gives a strut that feels stiff and transmits excessive shock loads to the airframe. The AMM's specific servicing sequence (deflate, check/add fluid, then charge nitrogen to the specified pressure at a specified extension) must be followed exactly, since checking these in the wrong order gives an inaccurate reading."}
    , {"heading": "Landing Gear Position Indication System Logic", "body": "Landing gear position indication relies on proximity sensors or mechanical switches at each gear leg confirming both the up-and-locked and down-and-locked positions, feeding cockpit indicators (commonly three green lights for down-and-locked) and triggering warning horns or lights if gear position is inconsistent with flap position or throttle setting during approach. A single faulty proximity sensor can cause a false gear-unsafe indication even though the gear is actually properly locked, requiring the technician to distinguish between an actual mechanical lock failure and a sensor/wiring fault through direct visual inspection of the lock mechanism rather than relying on the indication alone. Squat switch (weight-on-wheels) logic also interacts with the gear indication system, since many aircraft inhibit inadvertent retraction on the ground using squat switch input, and a faulty squat switch can either falsely allow ground retraction attempts or falsely prevent legitimate in-flight gear operation."},
    {"heading": "Landing Gear Uplock and Downlock Mechanism Function", "body": "Landing gear uplocks hold the gear securely in the retracted position against aerodynamic loads and vibration, while downlocks mechanically secure each gear leg in the extended position so it cannot collapse under ground loads even if hydraulic pressure is lost. Downlocks are typically spring-loaded mechanical hooks or over-center linkages that require a deliberate unlocking force (via the retraction actuator or an emergency release) to move out of the locked position, providing a fail-safe independent of hydraulic pressure. Uplock mechanisms often incorporate a release hook tripped by a dedicated uplock release actuator, and rigging of both locks must be verified so that the position indicating switches actuate precisely at full lock engagement, not merely near it, since a switch that indicates \u201clocked\u201d slightly before true mechanical lock engagement creates a dangerous false-safe condition."},
    {"heading": "Landing Gear Retraction Sequencing and Interlock Systems", "body": "Multi-gear retraction systems (nose plus main gear, or main gear with sequenced doors) require correctly timed sequencing so that gear doors open before the gear retracts and close only after the gear is fully stowed, preventing structural interference between the gear and doors during transit; sequencing valves, mechanical linkages, or electronic sequencing logic control this timing, and a sequencing fault can cause a gear or door to jam partway through a retraction or extension cycle. Ground safety interlocks (such as a squat switch or ground lock mechanism) prevent inadvertent gear retraction while the aircraft is on the ground, sensing gear strut compression or wheel spin-up to determine ground versus flight state, and interlock malfunction is a serious safety concern since a system that allows retraction while the aircraft is still on the ground could cause the aircraft to settle onto the ground uncommanded. Maintenance verification of sequencing and interlock function requires a full gear swing test (with the aircraft properly jacked and secured) observing correct door/gear timing and confirming ground safety interlocks correctly prevent retraction attempts when ground-sensed conditions are simulated."},
    {"heading": "Landing Gear Trunnion, Bushing, and Bearing Wear Inspection", "body": "The landing gear trunnion is the primary pivot structure connecting the gear leg to the airframe, and it carries the full weight and dynamic loads of landing impacts through bushings and bearings that permit retraction rotation while maintaining precise alignment. Over repeated landing cycles, these bushings and bearings wear, and excessive wear introduces free play that allows the gear leg to shift slightly under load, which can misalign wheel tracking, increase tire wear on one side, and in severe cases create binding or interference during retraction. Technicians inspect trunnion bushings using a dial indicator to measure radial play between the pin and bushing bore, or by direct measurement of bushing inner diameter against the mating pin outer diameter, comparing results to the maintenance manual's serviceable wear limits rather than relying on a visual or feel check alone, since play that seems acceptable by hand can still exceed the numeric limit. Bushings are typically a replaceable wear item designed to protect the more expensive trunnion structure from direct wear, and when a bushing is condemned it is pressed out and a new one installed per the specified interference fit and orientation, with the bore re-verified round and to size afterward. Lubrication interval and grease type at the trunnion pivot points is specified precisely because inadequate lubrication accelerates wear rate substantially, and using an incompatible grease can degrade elastomeric seals designed to keep contaminants out of the bearing surface. Any detected trunnion structure elongation or ovality in the pin bore itself, as opposed to bushing wear, is a structural finding requiring engineering evaluation rather than routine bushing replacement, since it indicates the load path through the structure itself has been compromised."}],
    "quiz": [ {"q": "Why must a landing gear position indication system sense actual mechanical lock state rather than merely the hydraulic command state?", "choices": ["Command state sensing is always more reliable", "Sensing only command state could show a false-safe 'down' indication for gear that is not actually mechanically locked", "Mechanical lock sensing is required only on older aircraft", "There is no meaningful difference between command state and actual lock state"], "answer": 1}, {"q": "Why must a gear-unsafe cockpit indication always be verified against the actual mechanical lock, not just trusted at face value?", "choices": ["Cockpit indications are always 100% reliable", "A single faulty proximity sensor can cause a false gear-unsafe indication even when the gear is properly locked", "Mechanical locks never actually fail", "Indication systems have no sensors involved"], "answer": 1, "explain": "A faulty sensor can trigger a false gear-unsafe warning even though the mechanical lock is functioning correctly, so technicians must visually confirm actual lock status rather than relying solely on the indication."},
      {"q": "Why must a shock strut's fluid level and nitrogen charge both be correct, not just one or the other?", "choices": ["Only fluid level matters", "An imbalance between fluid and gas charge causes incorrect strut performance even if extended height looks approximately right", "Only nitrogen pressure matters", "Shock struts don't use both fluid and gas"], "answer": 1, "explain": "Oleo-pneumatic struts rely on the correct balance of both hydraulic fluid and nitrogen gas charge; getting only one right can still produce a strut with the wrong shock-absorbing characteristics."},
      {"q": "A landing gear position indicator that fails to show 'gear down and locked' even though the gear is physically down often indicates:", "choices": ["A definite hydraulic pump failure", "A misaligned or faulty position/microswitch not sending the correct signal", "Low fuel", "A tire problem"], "answer": 1, "explain": "Position indication problems are frequently caused by a misrigged or faulty squat/position switch rather than an actual gear or hydraulic fault."},
      {"q": "What is the main advantage of tricycle gear over tailwheel gear?", "choices": ["Lighter weight always","Better ground handling and visibility","Requires no brakes","Works only on grass runways"], "answer": 1, "explain": "Tricycle gear generally offers better ground handling, visibility, and stability compared to tailwheel configurations."},
      {"q": "What does an oleo-pneumatic strut combine?", "choices": ["Two different metals","Compressed air/nitrogen with hydraulic fluid for shock absorption and damping","Electric motors and gears","Two separate tires"], "answer": 1, "explain": "Oleo struts use compressed gas for springing action and hydraulic fluid for damping to absorb shock loads."},
      {"q": "What allows gear extension if the primary retraction system fails?", "choices": ["Nothing - gear stays retracted","Emergency extension system (free-fall, backup hydraulic, or manual crank)","The autopilot","Speed brakes"], "answer": 1, "explain": "Emergency extension systems provide a backup means to get the gear down if the primary system malfunctions."},
      {"q": "What is the purpose of an anti-skid system?", "choices": ["Increase tire wear","Modulate brake pressure to prevent tire skidding and maximize braking efficiency","Increase touchdown speed","Reduce fuel consumption"], "answer": 1, "explain": "Anti-skid systems prevent wheel lockup/skidding by modulating brake pressure, improving stopping performance."},
      {"q": "Why is it important to check tire inflation when cold?", "choices": ["Cold tires are always overinflated","Tire pressure rises with heat/use, so cold-check gives the true baseline reading","It doesn't matter when checked","Warm tires read lower than actual"], "answer": 1, "explain": "Tire pressure increases with heat, so checking cold ensures an accurate baseline reading against the tire chart."},
    {"q": "Why are landing gear downlocks designed as mechanical hooks or over-center linkages rather than relying solely on hydraulic pressure?", "choices": ["Mechanical locks are cheaper to manufacture", "They provide a fail-safe that keeps the gear extended and locked even if hydraulic pressure is lost", "Hydraulic pressure alone would extend the gear too quickly", "Downlocks are purely for pilot indication and have no structural function"], "answer": 1},
    {"q": "What is the safety function of a ground interlock (such as a squat switch) in a landing gear retraction system?", "choices": ["It has no safety function and only indicates gear position to the cockpit", "It prevents inadvertent gear retraction while the aircraft is on the ground by sensing ground versus flight state", "It only functions to sequence door timing during retraction, not ground safety", "Ground interlocks are optional equipment not required on any aircraft"], "answer": 1},
    {"q": "Why do technicians measure trunnion bushing wear with a dial indicator or direct diameter measurement rather than relying on a feel check?", "choices": ["Play that seems acceptable by hand can still exceed the numeric wear limit specified in the maintenance manual", "Dial indicators are required by regulation for all landing gear inspections regardless of purpose", "Feel checks are more accurate than dial indicator measurements for bushing wear", "Bushing wear cannot be measured by any method other than a feel check"], "answer": 0}
    ]
  },
  {
    "id": "turbine_theory", "title": "Gas Turbine Theory & Types", "track": "powerplant", "icon": "&#x1F32A;",
    "sections": [
      {"heading": "Brayton Cycle Basics", "body": "Gas turbines operate on the <b>Brayton cycle</b>: air is compressed, fuel is added and burned at roughly constant pressure, and the resulting hot expanding gas drives a turbine and/or produces thrust. This is continuous combustion (unlike a reciprocating engine's intermittent combustion), giving turbines smoother operation and higher power-to-weight ratios."},
      {"heading": "Engine Types", "body": "<b>Turbojet</b>: all thrust from exhaust gas velocity. <b>Turbofan</b>: a large fan (bypassing much of the airflow around the core) provides most thrust with better fuel efficiency at subsonic speeds - the dominant type on modern airliners. <b>Turboprop</b>: a turbine drives a propeller through a reduction gearbox. <b>Turboshaft</b>: turbine power drives a shaft (helicopters, APUs, industrial use) rather than propulsive thrust directly."},
      {"heading": "Compressor Types", "body": "<b>Centrifugal</b> compressors use an impeller to accelerate air outward, good for smaller/simpler engines with fewer stages needed. <b>Axial</b> compressors use a series of rotating (rotor) and stationary (stator) blade rows to progressively compress air along the engine's axis - most efficient for large, high-thrust engines and dominant in modern turbofans."},
      {"heading": "Bypass Ratio & Efficiency", "body": "<b>Bypass ratio</b> compares the mass of air bypassing the core (through the fan) to the mass going through the core. High-bypass turbofans (common on airliners) prioritize fuel efficiency at high subsonic speed; low-bypass turbofans (military fighters) prioritize higher speed/thrust density at some efficiency cost."},
      {"heading": "Brayton Cycle in Practice", "body": "The gas turbine's Brayton cycle (compression, combustion at constant pressure, expansion/power extraction, exhaust) explains why compressor and turbine sections must be matched - if the turbine can't extract enough energy to properly drive the compressor, the engine will not reach its designed pressure ratio and efficiency suffers. Real-world deviations from the ideal cycle (compressor/turbine inefficiencies, pressure losses in the combustor, incomplete combustion) are why actual engines never achieve theoretical Brayton-cycle efficiency, and why small deviations in any single stage's condition (e.g., compressor fouling) measurably reduce overall engine performance."},
      {"heading": "Compressor Stall and Surge Mechanics", "body": "A compressor stall occurs when the airflow through one or more compressor stages separates from the blade surface (similar to a wing stall), disrupting smooth airflow and often producing an audible bang and a temporary loss of thrust/power; a full compressor surge is a more severe event where the disrupted airflow reverses direction momentarily. Both are usually triggered by rapid throttle movement, foreign object ingestion disrupting airflow, or a mechanical fault (damaged blades, fouled stages) reducing the stall margin the engine was designed with. Understanding this helps a mechanic interpret pilot reports of 'engine banging' or momentary power loss as a likely compressor stall/surge event requiring inspection, not a vague unexplained anomaly."}
    , {"heading": "Turbine Engine Thrust and Power Calculation Basics", "body": "Turbine engine thrust results from the net momentum change of air accelerated through the engine, calculated fundamentally as the mass flow rate of air (and fuel) multiplied by the change in velocity from inlet to exit, with additional pressure thrust contribution if the exhaust exits at a pressure different from ambient. Turboprop and turboshaft engines convert most of the gas generator's energy into shaft power to drive a propeller or rotor rather than jet thrust, measured in units like shaft horsepower or equivalent shaft horsepower, requiring a different performance evaluation approach than pure thrust-producing turbojets and turbofans. Understanding which parameter (thrust vs. shaft power) is the relevant performance metric for a given engine type is essential when evaluating whether an engine is meeting its rated performance during ground runs or troubleshooting a power complaint, since applying thrust-based evaluation criteria to a shaft-power engine (or vice versa) would give meaningless results."},
    {"heading": "Axial vs. Centrifugal Compressor Design Trade-offs", "body": "Centrifugal compressors accelerate air radially outward using an impeller before diffusing it to raise pressure, achieving a high pressure ratio per stage in a compact, rugged design that is more tolerant of foreign object damage, making them common on smaller turboshaft and turboprop engines and auxiliary power units. Axial compressors move air parallel to the engine centerline through alternating rows of rotating blades and stationary vanes, achieving lower pressure ratio per stage but allowing many stages to be stacked efficiently for very high overall pressure ratios with better airflow matching to a downstream axial turbine, which is why axial compressors dominate large turbofan and turbojet designs where overall efficiency and airflow matter more than compactness or FOD tolerance. Many engines use a combination, with a few centrifugal stages augmenting an axial compressor set to balance these trade-offs for the application."},
    {"heading": "Turbine Engine Thermodynamic Efficiency Factors and Losses", "body": "The theoretical Brayton cycle efficiency depends primarily on the overall pressure ratio and turbine inlet temperature, but real turbine engines fall short of ideal cycle efficiency due to several loss mechanisms. Component inefficiencies in the compressor and turbine—expressed as isentropic (adiabatic) efficiency—arise from aerodynamic losses like blade friction, tip clearance leakage, and flow separation, meaning real compression requires more work input and real expansion yields less work output than the ideal cycle predicts. Combustor pressure loss and incomplete combustion efficiency reduce the energy actually delivered to the gas stream. Mechanical losses from bearing friction and accessory gearbox power extraction further reduce net output. Propulsive efficiency, distinct from thermal efficiency, describes how effectively the engine converts its net power into useful thrust work on the aircraft, and is improved by higher bypass ratios that give exhaust velocities closer to aircraft flight speed, minimizing kinetic energy wasted in the exhaust wake. Overall engine efficiency is therefore the product of thermal efficiency (how well fuel energy converts to mechanical/kinetic energy) and propulsive efficiency (how well that energy converts to useful thrust work), which is why modern high-bypass turbofans achieve substantially better fuel efficiency than early low-bypass turbojets despite operating on the same basic Brayton cycle."},
    {"heading": "Variable Stator Vane Systems and Their Role in Compressor Performance", "body": "Variable stator vanes, fitted to many axial compressor designs in both commercial and military turbine engines, allow the angle of the stationary vanes ahead of or between compressor rotor stages to be adjusted, redirecting the airflow direction entering each rotor stage to maintain an efficient blade angle of attack across a wide range of compressor speeds and mass flow conditions. Without variable geometry, a multi-stage axial compressor designed for efficient operation at its design point would suffer severe compressor stall or surge at lower shaft speeds, since the airflow velocity and direction relative to the rotating blades changes dramatically as speed varies, quickly moving blade angle of attack outside the tolerable range. The variable stator vane system consists of individual vane rings whose angular position is controlled through a mechanical linkage driven by an actuator commanded by the engine control system, which schedules vane angle as a function of compressor speed and sometimes also inlet temperature, continuously optimizing the compressor's stage matching across the operational range. Maintenance of variable stator vane systems includes inspection of the vane pivots and bushings for wear that would introduce free play and prevent accurate vane positioning, verification of the actuator's range of motion and rigging against the engine manual's schedule, and inspection of the linkage rods and bellcranks for wear, corrosion, and security. A vane that is stuck in the wrong position or has excessive free play in its pivot can degrade a specific compressor stage's performance without triggering an obvious fault indication, making periodic rigging and wear checks important before marginal compressor performance or early surge onset becomes evident in operational data."}],
    "quiz": [ {"q": "Why do high-bypass turbofan engines generally achieve better fuel efficiency than low-bypass turbojets at typical airliner cruise speeds?", "choices": ["They burn a completely different type of fuel", "They produce most thrust by accelerating a large mass of fan air at relatively lower velocity, which is more propulsively efficient than a smaller mass at higher velocity", "Bypass ratio has no effect on fuel efficiency", "High-bypass engines produce no core exhaust thrust at all"], "answer": 1}, {"q": "What is the fundamental basis for turbine engine thrust calculation?", "choices": ["Fuel flow rate alone", "The mass flow rate of air multiplied by the change in velocity from inlet to exit, plus any pressure thrust", "Compressor RPM alone", "Turbine inlet temperature alone"], "answer": 1, "explain": "Thrust is fundamentally based on the momentum change of the air mass flow accelerated through the engine, with an additional pressure thrust term if exhaust pressure differs from ambient."},
      {"q": "A pilot report describing an audible 'bang' with momentary power loss during a rapid throttle movement most likely describes:", "choices": ["Normal engine operation", "A compressor stall or surge event that requires inspection", "A landing gear issue", "Normal fuel gauge fluctuation"], "answer": 1, "explain": "An audible bang with momentary power loss, especially following rapid throttle movement, is a classic symptom of a compressor stall or surge and warrants investigation."},
      {"q": "Why does compressor blade fouling (dirt/deposits buildup) measurably reduce overall gas turbine engine performance?", "choices": ["It has no effect on the Brayton cycle", "It reduces compressor efficiency, disrupting the pressure ratio the whole cycle depends on", "It only affects paint appearance", "It increases fuel efficiency"], "answer": 1, "explain": "Compressor fouling reduces compression efficiency, lowering the pressure ratio the entire Brayton cycle depends on and reducing overall engine performance."},
      {"q": "What thermodynamic cycle do gas turbines operate on?", "choices": ["Otto cycle","Brayton cycle","Diesel cycle","Rankine cycle"], "answer": 1, "explain": "Gas turbines use the Brayton cycle: continuous compression, combustion, and expansion."},
      {"q": "Which engine type provides most of its thrust via a large bypass fan?", "choices": ["Turbojet","Turbofan","Turboshaft","Ramjet"], "answer": 1, "explain": "Turbofans use a large fan to bypass most airflow around the core, producing most thrust with improved efficiency."},
      {"q": "What is a key advantage of axial compressors over centrifugal for large engines?", "choices": ["Lower cost only","Higher efficiency and better suited to large, high-thrust engines","Simpler construction","No stator blades needed"], "answer": 1, "explain": "Axial compressors offer higher efficiency and scalability, making them dominant in large modern turbofans."},
      {"q": "What does bypass ratio compare?", "choices": ["Fuel to oil ratio","Mass of air bypassing the core vs. mass going through the core","Compressor stages to turbine stages","Weight to thrust ratio"], "answer": 1, "explain": "Bypass ratio is the ratio of bypass airflow (through the fan, around the core) to core airflow."},
      {"q": "Why do continuous-combustion turbine engines generally run smoother than reciprocating engines?", "choices": ["They use less fuel","Combustion is continuous rather than intermittent, avoiding the pulsed power strokes of a piston engine","They have fewer moving parts","They operate at lower RPM"], "answer": 1, "explain": "Turbines have smooth, continuous combustion, unlike the pulsed power strokes of reciprocating piston engines."},
    {"q": "Why do centrifugal compressors remain common on smaller turboshaft engines and APUs despite axial compressors dominating large turbofans?", "choices": ["Centrifugal compressors are always more fuel efficient at any size", "Centrifugal compressors achieve high pressure ratio per stage in a compact, rugged, FOD-tolerant design well suited to smaller applications", "Axial compressors cannot be manufactured at small sizes", "There is no meaningful difference between the two compressor types"], "answer": 1},
    {"q": "Why do modern high-bypass turbofans achieve better overall efficiency than early low-bypass turbojets on the same Brayton cycle?", "choices": ["They operate at lower turbine inlet temperatures", "Higher bypass ratio improves propulsive efficiency by producing exhaust velocities closer to flight speed", "They use no compressor stages", "Overall efficiency is unrelated to bypass ratio"], "answer": 1},
    {"q": "Why are variable stator vanes used in axial compressor designs rather than fixed-angle stators alone?", "choices": ["They redirect airflow entering rotor stages to maintain an efficient blade angle of attack across the full speed range, preventing stall and surge at off-design conditions", "They allow the compressor to run at only a single fixed design speed without any adjustment", "They replace the need for any rotating compressor stages", "Variable stators are used only for noise reduction purposes, not for performance"], "answer": 0}
    ]
  },
  {
    "id": "engine_lubrication", "title": "Engine Lubrication Systems", "track": "powerplant", "icon": "&#x1FAD9;",
    "sections": [
      {"heading": "Lubrication Purposes", "body": "Engine oil reduces friction/wear between moving parts, carries away heat, seals piston rings (in reciprocating engines), cleans by carrying away contaminants to the filter, and in some systems, helps dampen vibration/noise. Turbine engines also use oil for bearing lubrication and, in constant-speed props/hydraulic units, as an actuating fluid."},
      {"heading": "Reciprocating Engine Lube Systems", "body": "Most reciprocating aircraft engines use a <b>wet-sump</b> system (oil stored in a pan/sump below the engine) or a <b>dry-sump</b> system (oil stored in a separate external tank, common on aerobatic and some high-performance engines to prevent oil starvation during inverted/high-G flight). Oil pumps, pressure relief valves, and filters/screens are common to both."},
      {"heading": "Turbine Engine Lube Systems", "body": "Turbine engines typically use a <b>recirculating pressure-fed system</b> with a separate oil tank, pressure pump, scavenge pumps (to return oil from bearings back to the tank), oil coolers (air or fuel-cooled), and filters. Oil consumption and pressure/temperature trends are closely monitored - abnormal trends often indicate developing bearing or seal problems well before failure."},
      {"heading": "Oil Analysis & Filtration", "body": "<b>Spectrometric oil analysis (SOA)</b> detects trace wearing metal particles in used oil, helping catch developing component wear before it becomes a failure. Filters have <b>bypass valves</b> that allow oil flow to continue (unfiltered) if the filter becomes clogged, preventing oil starvation - a clogged filter indicator/bypass warning signals the need for filter service."},
      {"heading": "Oil Analysis and Contamination Trends", "body": "Spectrometric oil analysis (SOAP) tracks trace metal levels (iron, copper, aluminum, chromium) in used oil samples over time; a sudden spike in a specific metal points to wear in the component made of that metal (e.g., rising iron suggests cylinder/piston ring wear, rising copper suggests bushing/bearing wear). A single elevated reading isn't necessarily alarming, but a clear upward trend across multiple samples is a strong early warning of developing internal wear, often catching a problem well before it produces a noticeable performance change."},
      {"heading": "Oil Cooler and Thermostatic Bypass Function", "body": "An oil cooler with a thermostatic bypass valve routes oil around the cooler when cold (allowing faster warm-up) and through the cooler once oil reaches operating temperature - a bypass valve stuck in the bypass position causes chronic oil overheating even with a perfectly clean, undamaged cooler, since oil never actually flows through it. Conversely, a valve stuck in the cooling position can cause the engine to run with abnormally cold oil during climb/cold weather operation, affecting oil film strength and increasing wear during that period."}
    , {"heading": "Oil Cooler Bypass and Thermostatic Control Failures", "body": "Oil cooler thermostatic bypass valves route oil around the cooler when cold to speed engine warm-up and prevent over-cooling, then progressively route oil through the cooler as operating temperature rises; a bypass valve stuck open can cause chronic high oil temperature since oil never reaches the cooler, while a valve stuck closed can cause overcooling and thickened oil at startup with reduced flow to critical bearings. Diagnosing a bypass valve fault requires monitoring oil temperature trend against ambient conditions and flight phase, since a valve that responds sluggishly rather than failing completely can be harder to detect than an outright stuck valve. Cooler core blockage from debris or oil sludge can mimic a stuck-open bypass valve symptom, so technicians must inspect the cooler core itself, not just the bypass valve, when troubleshooting chronic high oil temperature."},
    {"heading": "Oil Pressure Relief Valve Function and Adjustment", "body": "The oil pressure relief valve protects the lubrication system from excessive pressure, particularly during cold starts when high oil viscosity can otherwise drive pressure well beyond safe limits before the oil warms up. The valve is a spring-loaded ball or poppet set to crack open at a specified pressure, diverting excess oil flow back to the inlet side of the pump or to the sump rather than through the engine's lubrication passages. A relief valve stuck closed causes abnormally high oil pressure and can rupture lines or seals, while a valve stuck open or a weakened spring causes chronically low oil pressure even with a healthy pump, sometimes misdiagnosed as pump wear. Adjustable relief valves use a shim stack or adjusting screw to set cracking pressure, and after any adjustment the system must be run and pressure verified against the AMM limits across the normal operating range, not just at idle."},
    {"heading": "Oil Pump Types and Pressure Regulation Methods", "body": "Most reciprocating and turbine engine oil systems use a positive-displacement gear pump (spur gear or lobe-type) driven off the engine's accessory section, delivering a flow that increases with engine speed; because a gear pump's output would otherwise increase oil pressure excessively at high RPM, a pressure relief valve diverts excess flow back to the inlet or sump once a set pressure is reached, allowing pump output to exceed system needs at high speed without pressure rising unchecked. Pump wear (gear tooth wear, case wear increasing internal clearance) reduces volumetric efficiency, showing up as low oil pressure especially at idle/low RPM where flow margin is smallest, while a pump with a sheared drive shaft or stripped drive gear produces zero oil pressure regardless of RPM. Because oil pump failure analysis at overhaul or troubleshooting must distinguish between pump wear, a failed relief valve, and an oil supply/filter restriction upstream of the pump, technicians should check inlet screen/filter condition before assuming a low-pressure fault is pump-related."},
    {"heading": "Wet Sump vs Dry Sump Lubrication System Design", "body": "Reciprocating and turbine engines use either wet sump or dry sump lubrication system architecture, each with distinct advantages and maintenance considerations. Wet sump systems store the oil supply directly in a sump or pan attached to the bottom of the engine, from which the oil pump draws oil directly; this design is simpler and lighter but subjects the oil supply to engine attitude changes and acceleration forces, such as during aerobatic maneuvers or steep climbs and descents, that can cause the oil pickup to become uncovered, leading to a momentary loss of oil pressure or pump cavitation. Dry sump systems use a separate remotely mounted oil tank or reservoir, with a scavenge pump system that continuously returns oil from the engine's internal sump back to the external tank, decoupling the oil supply from being directly subject to engine-mounted sump attitude limitations and allowing a larger oil capacity and better cooling since oil can be routed through external coolers before returning to the tank; this design is more complex, requiring both pressure and scavenge pump stages, but is common on turbine engines and aerobatic or inverted-capable reciprocating engines specifically because of its attitude tolerance. Maintenance of a dry sump system requires attention to both the pressure and scavenge sides of the system, since a scavenge pump or line problem can cause oil to accumulate in the engine sump rather than properly returning to the tank, potentially leading to oil starvation at the tank despite adequate total oil quantity in the system."}],
    "quiz": [ {"q": "What symptom would result from an oil cooler thermostatic bypass valve stuck in the bypass position?", "choices": ["Oil temperature would run persistently high since oil never flows through the cooler", "Oil pressure would immediately drop to zero", "The engine would fail to start", "Oil temperature would remain artificially low"], "answer": 0}, {"q": "What happens if an oil cooler thermostatic bypass valve is stuck open?", "choices": ["Oil never reaches the cooler, causing chronic high oil temperature", "Oil temperature drops dangerously low", "The engine loses all oil pressure immediately", "Fuel consumption decreases"], "answer": 0, "explain": "A bypass valve stuck open routes oil around the cooler continuously, preventing proper cooling and leading to chronically elevated oil temperatures."},
      {"q": "An oil cooler thermostatic bypass valve stuck in the bypass position would most likely cause:", "choices": ["Perfectly normal oil temperature", "Chronic oil overheating, since oil never actually flows through the cooler", "Oil that is too cold", "No effect on oil temperature"], "answer": 1, "explain": "If the bypass valve is stuck routing oil around the cooler, the oil never receives cooling, leading to chronic overheating even if the cooler itself is undamaged."},
      {"q": "A gradually rising trend of a specific trace metal across multiple oil analysis samples (rather than one isolated high reading) is significant because it:", "choices": ["Is always a lab error", "Indicates ongoing, worsening wear of the component made from that metal", "Means the oil needs no more attention", "Only affects oil color"], "answer": 1, "explain": "A consistent upward trend, rather than a single spike, is a reliable early indicator of progressive wear in a specific component."},
      {"q": "What is a key purpose of engine oil besides reducing friction?", "choices": ["Increasing engine weight","Carrying away heat and contaminants","Reducing fuel octane requirements","Increasing compression ratio"], "answer": 1, "explain": "Beyond lubrication, oil carries away heat and contaminants (to the filter), among other functions."},
      {"q": "Why do some aerobatic aircraft use a dry-sump oil system?", "choices": ["It's cheaper","To prevent oil starvation during inverted or high-G flight","It requires no oil pump","It eliminates the need for filters"], "answer": 1, "explain": "Dry-sump systems with external tanks help maintain oil supply during inverted/high-G maneuvers where a wet sump might starve the pump."},
      {"q": "What is the purpose of a scavenge pump in a turbine lube system?", "choices": ["To add fuel to the oil","To return oil from bearings back to the oil tank","To measure oil temperature","To filter the fuel"], "answer": 1, "explain": "Scavenge pumps return oil from bearing sumps back to the main oil tank in a turbine engine's recirculating system."},
      {"q": "What does spectrometric oil analysis (SOA) detect?", "choices": ["Fuel contamination only","Trace wearing metal particles indicating developing component wear","Tire pressure","Cabin altitude"], "answer": 1, "explain": "SOA detects trace metal particles in oil, helping identify developing wear issues before failure."},
      {"q": "What is the purpose of a filter bypass valve?", "choices": ["To stop oil flow completely","To allow oil flow to continue (unfiltered) if the filter clogs, preventing oil starvation","To increase oil pressure permanently","To cool the oil"], "answer": 1, "explain": "A bypass valve prevents oil starvation by allowing flow around a clogged filter, though then unfiltered."},
    {"q": "An engine shows chronically low oil pressure across all power settings even though the oil pump tests within limits. What component should be suspected?", "choices": ["The oil pressure relief valve stuck open or with a weakened spring", "The propeller governor", "The magneto timing", "The exhaust valve clearance"], "answer": 0},
    {"q": "An engine shows low oil pressure specifically at idle/low RPM, with acceptable pressure at higher power settings. What does this pattern most likely suggest?", "choices": ["A completely sheared oil pump drive shaft", "Oil pump wear reducing volumetric efficiency, which is most noticeable where flow margin is smallest at low RPM", "The oil pressure relief valve is stuck closed", "This pattern indicates normal operation with no fault present"], "answer": 1},
    {"q": "Why are dry sump lubrication systems commonly used on aerobatic or inverted-capable reciprocating engines?", "choices": ["Dry sump systems are simpler and lighter than wet sump systems", "They decouple the oil supply from engine attitude limitations that would otherwise uncover the oil pickup during maneuvers", "Dry sump systems require no scavenge pump", "Wet sump systems handle inverted flight better"], "answer": 1}
    ]
  }
]

EXT11_FLASHCARDS = [
  {"front": "Galvanic corrosion cause", "back": "Two dissimilar metals in contact with an electrolyte (e.g., moisture)."},
  {"front": "Intergranular corrosion", "back": "Attacks grain boundaries inside the metal; often invisible from the surface until advanced."},
  {"front": "Corrosion removal limits reference", "back": "The Structural Repair Manual (SRM)."},
  {"front": "Pascal's Law", "back": "Pressure applied to a confined fluid transmits equally in all directions - basis of hydraulic force multiplication."},
  {"front": "Hydraulic accumulator purpose", "back": "Stores pressurized fluid to dampen spikes and provide backup pressure."},
  {"front": "Closed-center hydraulic system", "back": "Pump maintains static pressure with valves closed until an actuator is commanded."},
  {"front": "Oleo-pneumatic strut", "back": "Combines compressed gas (springing) with hydraulic fluid (damping) to absorb landing shock."},
  {"front": "Anti-skid system purpose", "back": "Modulates brake pressure to prevent tire skidding and maximize braking efficiency."},
  {"front": "Brayton cycle", "back": "Continuous compression, combustion, and expansion cycle used by gas turbine engines."},
  {"front": "Turbofan thrust source", "back": "Mostly from a large bypass fan; core provides the rest plus fan drive power."},
  {"front": "Bypass ratio", "back": "Ratio of air bypassing the core (through the fan) to air going through the core."},
  {"front": "Axial vs centrifugal compressor", "back": "Axial: rotor/stator stages along engine axis, efficient for large engines. Centrifugal: impeller, simpler, fewer stages."},
  {"front": "Dry-sump oil system use case", "back": "Aerobatic/high-performance engines - prevents oil starvation during inverted/high-G flight."},
  {"front": "Scavenge pump", "back": "Returns oil from turbine engine bearings back to the oil tank."},
  {"front": "Spectrometric Oil Analysis (SOA)", "back": "Detects trace wearing metal particles in oil, revealing developing wear before failure."},
  {"front": "Oil filter bypass valve", "back": "Allows unfiltered oil flow if the filter clogs, preventing oil starvation."},
]

EXT11_GLOSSARY = [
  {"term": "Pitting Corrosion", "def": "Localized corrosion forming small pits, often occurring under coatings or in crevices."},
  {"term": "Corrosion-Inhibiting Compound (CIC)", "def": "A protective compound applied to fay surfaces and unpressurized bays to prevent corrosion."},
  {"term": "Pascal's Law", "def": "Pressure applied to a confined fluid is transmitted equally in all directions."},
  {"term": "Open-Center Hydraulic System", "def": "A system where fluid circulates continuously at low pressure when no actuator is commanded."},
  {"term": "Skydrol", "def": "A phosphate-ester based hydraulic fluid; must not be mixed with mineral-based fluids like MIL-H-5606."},
  {"term": "Ground Loop", "def": "An uncontrolled swerve/rotation on the ground, more common with tailwheel gear configurations."},
  {"term": "Uplock/Downlock", "def": "Mechanical locks that secure retractable landing gear in the up or down position."},
  {"term": "Brayton Cycle", "def": "The thermodynamic cycle of continuous compression, combustion, and expansion used by gas turbines."},
  {"term": "High-Bypass Turbofan", "def": "A turbofan with a high ratio of fan-bypassed air to core air, optimized for subsonic fuel efficiency."},
  {"term": "Centrifugal Compressor", "def": "A compressor using an impeller to accelerate air outward; simpler, used in smaller turbine engines."},
  {"term": "Wet-Sump Oil System", "def": "An oil system storing oil in a pan/sump directly below the engine."},
  {"term": "Dry-Sump Oil System", "def": "An oil system using a separate external oil tank, common in aerobatic/high-performance engines."},
  {"term": "Spectrometric Oil Analysis (SOA)", "def": "An oil test detecting trace wearing metal particles to reveal developing component wear."},
  {"term": "Filter Bypass Valve", "def": "A valve that allows oil to bypass a clogged filter (unfiltered) to prevent oil starvation."},
]
