"""Aviation Maintenance Academy - Wave 5 content pack.
Adds 5 new modules balanced across tracks. Merged in academy_data.py.
"""

EXT9_MODULES = [
  {
    "id": "human_factors", "title": "Human Factors & Maintenance Error", "track": "general", "icon": "&#x1F9E0;",
    "sections": [
      {"heading": "The Dirty Dozen", "body": "A well-known list of the twelve most common human factors that lead to maintenance errors: lack of communication, complacency, lack of knowledge, distraction, lack of teamwork, fatigue, lack of resources, pressure, lack of assertiveness, stress, lack of awareness, and norms. Recognizing these in yourself and coworkers is the first step to preventing errors."},
      {"heading": "SHELL Model", "body": "The SHELL model frames human factors around interfaces: <b>Software</b> (procedures, manuals), <b>Hardware</b> (tools, equipment), <b>Environment</b> (lighting, noise, weather), <b>Liveware</b> (the people involved - self and others). Most errors occur at the boundary where Liveware interacts poorly with one of the other elements."},
      {"heading": "Fatigue & Shift Work", "body": "Fatigue degrades attention, decision-making, and memory - comparable to alcohol impairment at extreme levels. Shift work, especially rotating or night shifts, disrupts circadian rhythm. Fatigue risk management includes adequate rest periods, workload planning, and self-reporting when unfit for safety-critical tasks."},
      {"heading": "Error-Reduction Tools", "body": "Techniques include: written <b>checklists</b> and sign-offs, <b>duplicate/independent inspections</b> for critical systems, <b>task cards</b> that force step-by-step documentation, and a strong <b>reporting culture</b> (non-punitive) that surfaces near-misses before they become incidents. Distraction management (e.g., 'sterile' focus periods for critical steps) also reduces skipped-step errors."}
    ],
    "quiz": [
      {"q": "The 'Dirty Dozen' in maintenance human factors refers to:", "choices": ["Twelve types of aircraft damage","Twelve common human factors that lead to maintenance errors","A tool inventory list","Twelve FAA regulations"], "answer": 1, "explain": "The Dirty Dozen is a list of twelve human factors (e.g., fatigue, complacency, distraction) commonly linked to maintenance errors."},
      {"q": "In the SHELL model, what does the 'L' in the center stand for?", "choices": ["Liveware (people)","Lighting","Logistics","Landing gear"], "answer": 0, "explain": "The central Liveware represents the person performing the task, interacting with Software, Hardware, and Environment."},
      {"q": "Extreme fatigue can impair performance comparably to:", "choices": ["Caffeine overuse","Alcohol impairment","Overtraining","Excess vitamin intake"], "answer": 1, "explain": "Research shows severe fatigue can degrade performance to a degree comparable with alcohol intoxication."},
      {"q": "Why are duplicate/independent inspections required on critical systems?", "choices": ["To slow down work","To catch errors a single inspector might miss","To increase paperwork for its own sake","They are optional"], "answer": 1, "explain": "A second, independent set of eyes catches errors the original mechanic may be blind to due to expectation bias."},
      {"q": "A non-punitive reporting culture primarily helps by:", "choices": ["Hiding mistakes","Surfacing near-misses and hazards before they cause an incident","Reducing paperwork","Increasing overtime"], "answer": 1, "explain": "When people aren't punished for honest reporting, hazards and near-misses get surfaced and corrected proactively."}
    ]
  },
  {
    "id": "nde_inspection", "title": "Nondestructive Inspection (NDI/NDT)", "track": "airframe", "icon": "&#x1F50E;",
    "sections": [
      {"heading": "Visual & Dye Penetrant", "body": "<b>Visual inspection</b> (aided by mirrors, borescopes, magnification) is the most common NDI method. <b>Dye penetrant</b> inspection reveals surface-breaking cracks: penetrant is applied, excess removed, then a developer draws penetrant back out of any crack, showing a visible indication - effective on non-porous materials like aluminum and steel."},
      {"heading": "Magnetic Particle Inspection", "body": "Used on ferromagnetic materials only (steel, some alloys). The part is magnetized, then iron particles are applied; particles cluster at flux leakage points caused by surface or near-surface cracks, revealing the defect. Cannot be used on aluminum, titanium, or other non-magnetic materials."},
      {"heading": "Eddy Current & Ultrasonic", "body": "<b>Eddy current</b> inspection induces electrical currents in conductive material via a probe coil; cracks and corrosion disrupt the current, changing the probe's signal - good for surface/near-surface flaws, especially around fastener holes. <b>Ultrasonic</b> inspection sends high-frequency sound waves through material; reflections from internal flaws or the back wall reveal thickness loss, delaminations, or subsurface defects."},
      {"heading": "Radiographic (X-ray) Inspection", "body": "X-ray/radiographic inspection passes radiation through a part onto film or a digital detector, revealing internal defects, corrosion, or foreign objects by density differences. Requires strict radiation safety controls and is often used for spot welds, composite structures, and complex castings/forgings."},
      {"heading": "Method Selection Logic", "body": "Choosing an NDT method depends on the flaw type and material: <b>dye penetrant</b> only finds surface-breaking flaws on non-porous materials; <b>magnetic particle</b> finds surface/near-surface flaws but only on ferromagnetic materials; <b>eddy current</b> is fast for surface cracks on conductive metals and works through thin coatings; <b>ultrasonic</b> finds internal/subsurface flaws and measures thickness; <b>radiography (X-ray)</b> reveals internal defects and is often the only method for complex internal geometry, but requires strict radiation safety controls. Technique selection is specified by the SRM/NDT manual, not left to preference."},
      {"heading": "Surface Preparation for NDT Accuracy", "body": "NDT method effectiveness depends heavily on proper surface preparation - dye penetrant requires a clean, dry surface free of paint/coating (since penetrant can't reach a crack under a sealed coating), magnetic particle requires removal of any non-magnetic coating thick enough to mask the magnetic field indication, and ultrasonic requires a coupling medium (gel) and reasonably smooth surface for accurate sound transmission. Skipping or rushing surface prep is a common root cause of a false-negative NDT result - the part actually had a defect, but the inspection technique couldn't detect it due to inadequate preparation, not because the method itself failed."}
    , {"heading": "Ultrasonic Thickness Testing Applications", "body": "Ultrasonic thickness testing measures remaining material thickness in corroded or eroded structure by timing the sound wave's round-trip travel through the material, providing a quantitative measurement where visual inspection can only confirm that thinning has occurred without knowing the remaining margin against minimum thickness limits. This technique is especially valuable for detecting internal corrosion on the back side of skin panels or in areas where corrosion has progressed from the inside out without yet breaking through to a visually inspectable surface. Proper technique requires appropriate coupling gel to ensure sound wave transmission into the material, and calibration against a known-thickness reference block matching the material type being inspected, since sound travels at different speeds through different alloys and an uncalibrated reading can give a false sense of remaining material thickness."},
    {"heading": "Liquid Penetrant Inspection Sensitivity Levels and Selection", "body": "Liquid penetrant inspection materials are classified by sensitivity level (from Level 1, lowest, to Level 4, highest per common specifications) based on their ability to detect progressively finer discontinuities, with higher-sensitivity penetrants able to reveal smaller cracks but also more prone to false indications from surface irregularities, machining marks, or inadequate cleaning. Selecting the correct sensitivity level and penetrant/developer system is specified by the applicable NDT procedure for the specific part and defect type being sought, and using an unnecessarily high sensitivity level on a rough-surfaced part can generate excessive false or nonrelevant indications that obscure true defects and waste inspection time. Water-washable, post-emulsifiable, and solvent-removable penetrant systems each have specific cleaning and application requirements, and mixing incompatible penetrant/developer/remover combinations from different systems can produce inaccurate or invalid results."},
    {"heading": "Radiographic Inspection Film Density and Exposure Technique", "body": "Radiographic (X-ray) inspection quality depends on achieving correct film density (the degree of film darkening) within a specified range that provides adequate contrast to reveal internal defects without being so dark or light that fine detail is lost, controlled by balancing X-ray tube voltage/current, exposure time, source-to-film distance, and film speed/type for the specific material thickness and density being radiographed. Image quality indicators (IQIs, small wire or hole-type gauges of known dimensions placed on the part during exposure) are radiographed alongside the part and must be visible on the resulting film at a specified sensitivity level, providing objective proof that the exposure technique was adequate to reveal a defect of the size the inspection is intended to detect, rather than relying on the inspector's subjective judgment of image quality alone. Because radiographic inspection involves ionizing radiation, exposure technique also involves radiation safety procedures (exclusion zones, dosimetry, shielding) that are a regulatory requirement distinct from, but performed alongside, the technical inspection procedure itself."},
    {"heading": "Magnetic Particle Inspection: Wet Continuous vs Dry Residual Method Selection", "body": "Magnetic particle inspection can be performed using either the wet method, where iron particles are suspended in a liquid carrier and applied while the magnetizing current is active, known as the continuous method, or the dry method, where finely divided dry iron particles are applied as a powder, typically with the magnetizing current also active during application. The wet continuous method offers higher sensitivity for detecting very fine surface discontinuities because the liquid carrier allows particles to move freely and align precisely along leakage field lines, making it the preferred method for detecting fine fatigue cracks in critical rotating components such as crankshafts and gear teeth. The dry method is generally preferred for detecting subsurface discontinuities somewhat below the surface and for inspecting rough or large surfaces in field conditions where wet bath equipment is impractical, since dry particles can be applied without the need for a recirculating bath system. Fluorescent wet particles viewed under ultraviolet black light in a darkened inspection booth provide the highest sensitivity combination available for magnetic particle inspection, and this combination is specified for the most critical rotating and structural components in many maintenance manuals. Regardless of method, the inspector must select the correct magnetizing technique, either circular magnetization for detecting longitudinal discontinuities or longitudinal magnetization for detecting transverse and circular discontinuities, since a discontinuity oriented parallel to the magnetic field lines will not produce a detectable leakage field and can be missed entirely even though particles were correctly applied. Demagnetization of the part after inspection is required in most applications, since residual magnetism can attract ferrous debris during service, interfere with compass or magnetic sensor readings nearby, or cause arc-like erosion at bearing surfaces from magnetized particle attraction."},
    {"heading": "Acoustic Emission Testing Principles for Structural Health Monitoring", "body": "Acoustic emission (AE) testing is a nondestructive evaluation method that detects transient elastic waves generated by sudden energy release within a material, such as crack growth, fiber breakage in composites, or corrosion pit formation. Unlike ultrasonic testing, which actively transmits sound waves through a part, AE testing is passive, using sensitive piezoelectric sensors mounted on the structure to listen for waves generated by the material itself as it is loaded or as damage progresses. AE testing is particularly valuable for monitoring pressure vessels, composite structures, and large areas during proof load testing, since a single sensor array can monitor a broad structural area simultaneously rather than requiring point-by-point scanning as with conventional ultrasonic methods. Signal analysis techniques evaluate the amplitude, frequency content, and arrival time at multiple sensors to characterize and locate the source of detected emissions through triangulation. AE testing requires careful discrimination between genuine structural emissions and background noise from sources such as mechanical rattling, electromagnetic interference, or fluid flow, making sensor placement and signal filtering critical to reliable results."},
    {"heading": "Inspection Reporting Standards and Defect Disposition Documentation", "body": "Nondestructive testing inspection reports must document not only whether a defect was found but sufficient detail about the finding's location, size, orientation, and characterization to support an accurate engineering disposition decision regarding whether the part is serviceable, repairable, or must be rejected. Report standards typically specify required elements including the specific inspection method and equipment settings used, calibration reference standard employed, the inspector's certification level, and a clear description or sketch showing the defect's precise location relative to identifiable part features, since a disposition decision made based on an inadequately documented finding risks either an overly conservative rejection of a serviceable part or, more concerning, an inadequate assessment of a defect that actually requires rejection. Photographic or video documentation of significant findings, where practical, supplements written descriptions and provides an objective record that can be reviewed by engineering personnel who were not present during the original inspection. Maintaining consistent, thorough inspection reporting standards across an organization's NDT program is essential not only for the immediate disposition decision but for building a reliable historical record that supports future trend analysis and repeat inspection comparison."}],
    "quiz": [ {"q": "Why must an ultrasonic thickness testing instrument be set to the correct sound velocity for the material being inspected?", "choices": ["Sound velocity setting only affects display brightness", "Using an incorrect material sound velocity setting produces systematically wrong thickness readings even with correct technique", "All materials have identical sound velocity so this setting never matters", "The sound velocity setting is only relevant for composite materials"], "answer": 1}, {"q": "What is a key advantage of ultrasonic thickness testing over visual inspection for corrosion assessment?", "choices": ["It is faster but less accurate", "It provides a quantitative remaining thickness measurement rather than just confirming thinning occurred", "It requires no calibration ever", "It only works on painted surfaces"], "answer": 1, "explain": "Ultrasonic thickness testing gives a specific quantitative measurement of remaining material thickness, allowing comparison against minimum thickness limits, unlike visual inspection alone."},
      {"q": "A false-negative NDT result (missing a real defect) is often traced back to:", "choices": ["The NDT method being fundamentally flawed", "Inadequate surface preparation preventing the method from properly detecting the defect", "Too much surface preparation", "NDT methods never produce false negatives"], "answer": 1, "explain": "Improper or rushed surface preparation is a common cause of false-negative NDT results, since the technique may be physically unable to detect a defect through an unprepared surface."},
      {"q": "Which NDT method can detect surface-breaking cracks but only on ferromagnetic materials?", "choices": ["Dye penetrant", "Magnetic particle inspection", "Ultrasonic", "Radiography"], "answer": 1, "explain": "Magnetic particle inspection relies on magnetizing the part and only works on ferromagnetic (magnetic) materials."},
      {"q": "Dye penetrant inspection is effective for detecting:", "choices": ["Internal voids deep in a part","Surface-breaking cracks on non-porous materials","Magnetic field strength","Fuel contamination"], "answer": 1, "explain": "Dye penetrant reveals cracks that break the surface of a non-porous material by capillary action drawing dye back out."},
      {"q": "Magnetic particle inspection can only be used on:", "choices": ["Any material","Ferromagnetic materials like steel","Composites only","Plastics"], "answer": 1, "explain": "Magnetic particle inspection relies on magnetizing the part, so it only works on ferromagnetic materials."},
      {"q": "Eddy current inspection is especially useful around:", "choices": ["Fastener holes for surface/near-surface flaws","Fuel tank interiors only","Tire pressure checks","Cabin pressurization seals"], "answer": 0, "explain": "Eddy current probes are commonly used to detect cracks around fastener holes and other surface/near-surface flaws."},
      {"q": "Ultrasonic inspection detects flaws by:", "choices": ["Measuring color change","Analyzing reflections of high-frequency sound waves","Applying magnetic particles","Using dye penetrant"], "answer": 1, "explain": "Ultrasonic inspection sends sound waves into the material and interprets reflections to find internal or subsurface flaws."},
      {"q": "Radiographic (X-ray) inspection is often chosen for:", "choices": ["Simple visual checks","Complex castings, spot welds, or composite structures where internal defects must be seen","Measuring cable tension","Checking oil pressure"], "answer": 1, "explain": "X-ray inspection reveals internal defects via density differences and is common for castings, welds, and composites."},
    {"q": "Why might using an unnecessarily high-sensitivity liquid penetrant on a rough-surfaced part be counterproductive?", "choices": ["Higher sensitivity penetrants are always cheaper and should be used regardless", "It can generate excessive false or nonrelevant indications from surface irregularities that obscure true defects", "High-sensitivity penetrants cannot detect any defects on rough surfaces", "Sensitivity level has no effect on the number of indications produced"], "answer": 1},
    {"q": "Why are image quality indicators (IQIs) radiographed alongside the part being inspected rather than relying on the inspector's subjective judgment of the film?", "choices": ["IQIs serve no technical purpose and are only a regulatory formality", "IQIs provide objective proof that the exposure technique was adequate to reveal a defect of the intended detection size", "IQIs are only used to calibrate the X-ray machine before any inspections begin", "Radiographic film density has no relationship to defect detection capability"], "answer": 1},
    {"q": "Why must a discontinuity's orientation be considered when selecting circular versus longitudinal magnetization for magnetic particle inspection?", "choices": ["A discontinuity oriented parallel to the magnetic field lines produces no detectable leakage field and can be missed", "Magnetization direction has no effect on which discontinuities are detectable", "Circular magnetization always detects every discontinuity orientation equally well", "Discontinuity orientation only matters for the dry method, not the wet method"], "answer": 0},
    {"q": "How does acoustic emission testing fundamentally differ from conventional ultrasonic testing?", "choices": ["AE testing requires immersion in water while ultrasonic does not", "AE testing is passive, listening for waves generated by the material itself, while ultrasonic testing actively transmits sound waves into the part", "AE testing can only be used on metals", "There is no meaningful difference"], "answer": 1},
    {"q": "Why must NDT inspection reports document defect location, size, and characterization in detail?", "choices": ["Report detail has no bearing on disposition decision accuracy", "Insufficient documentation risks either overly conservative rejection of a serviceable part or inadequate assessment of a defect requiring rejection", "Inspection reports only need to state pass or fail with no other detail", "Disposition decisions are made independent of any inspection report content"], "answer": 1}
    ]
  },
  {
    "id": "ice_rain_protection", "title": "Ice & Rain Protection Systems", "track": "airframe", "icon": "&#x2744;",
    "sections": [
      {"heading": "Types of Ice Hazards", "body": "<b>Structural icing</b> forms on wings, tail, and other surfaces, disrupting airflow and adding weight/drag. <b>Induction icing</b> forms in the engine air intake or carburetor, restricting airflow or fuel/air mixture. <b>Pitot/static icing</b> blocks airspeed and altitude sensing, a critical instrument hazard."},
      {"heading": "Anti-Ice vs. De-Ice", "body": "<b>Anti-ice</b> systems prevent ice from forming in the first place (e.g., continuously heated pitot probes, bleed-air heated wing leading edges). <b>De-ice</b> systems allow a small amount of ice to form, then remove it periodically (e.g., pneumatic boots that inflate/deflate to crack and shed ice, or electrically heated elements cycled on a timer)."},
      {"heading": "Pneumatic Boot Systems", "body": "Rubber boots on the leading edge inflate with engine bleed air or a pneumatic pump in a specific sequence, cracking accumulated ice which is then carried away by airflow. Boots must be inspected for cracking, deterioration, and proper adhesion; improper inflation sequencing can actually 'ice bridge' if boots are cycled too early on some designs."},
      {"heading": "Windshield & Rain Protection", "body": "Heated windshields prevent ice formation and fogging while providing some bird-strike resistance. Rain removal uses <b>hydrophobic coatings</b>, mechanical <b>wipers</b>, or high-velocity <b>bleed-air/pneumatic rain removal</b> systems that blast rain off the windshield surface at speed."}
    ],
    "quiz": [
      {"q": "Induction icing primarily affects:", "choices": ["Wing leading edges only","Engine air intake/carburetor airflow or fuel-air mixture","Cabin windows","Landing gear doors"], "answer": 1, "explain": "Induction icing forms in the engine's air intake or carburetor, restricting airflow or disrupting the fuel/air mixture."},
      {"q": "What is the key difference between anti-ice and de-ice systems?", "choices": ["No difference","Anti-ice prevents ice formation; de-ice allows some ice then removes it periodically","De-ice is only for engines","Anti-ice is only electrical"], "answer": 1, "explain": "Anti-ice systems run continuously to prevent ice; de-ice systems let a small amount form, then shed it periodically."},
      {"q": "How do pneumatic deicing boots remove ice?", "choices": ["By melting it with heat","By inflating/deflating in sequence to crack and shed accumulated ice","By spraying de-icing fluid","By vibrating at high frequency"], "answer": 1, "explain": "Pneumatic boots cyclically inflate to crack the ice bond, then airflow carries the shed ice away."},
      {"q": "What can happen if pneumatic boots are cycled too early on certain designs?", "choices": ["Nothing, it's always safe","'Ice bridging' where a shell of ice forms over the inflated boot shape","Improved efficiency","Reduced drag"], "answer": 1, "explain": "Cycling too early can create an ice bridge that the boot can no longer break, reducing deicing effectiveness."},
      {"q": "Which hazard specifically threatens airspeed and altitude indications?", "choices": ["Structural icing on the tail","Pitot/static icing","Windshield fogging","Induction icing"], "answer": 1, "explain": "Pitot/static icing blocks the sensing ports needed for accurate airspeed and altitude information."}
    ]
  },
  {
    "id": "recip_overhaul", "title": "Reciprocating Engine Overhaul Practices", "track": "powerplant", "icon": "&#x1F527;",
    "sections": [
      {"heading": "Overhaul Triggers", "body": "Reciprocating engines are typically overhauled at a manufacturer-recommended <b>TBO (Time Between Overhaul)</b> in hours, or sooner if a qualifying event occurs (sudden stoppage, over-temperature, metal in oil, prop strike). TBO is a recommendation for most operators (not mandatory under Part 91) but often mandatory under Part 135/121 operations or per an approved maintenance program."},
      {"heading": "Teardown & Inspection", "body": "Overhaul disassembles the engine completely; parts are cleaned, then inspected using NDI methods (magnetic particle for steel parts, dye penetrant for aluminum) against manufacturer service limits. Parts exceeding wear limits are replaced; crankshafts and camshafts are commonly magnetic-particle inspected for cracks."},
      {"heading": "Reassembly & Break-In", "body": "Reassembly follows the overhaul manual's torque values and sequences exactly. New rings and reconditioned/new cylinders often require a specific <b>break-in procedure</b> (mineral oil, higher power settings initially) to properly seat rings against cylinder walls - improper break-in can cause glazed cylinders and excess oil consumption for the engine's life."},
      {"heading": "Run-In & Documentation", "body": "After reassembly, the engine undergoes a run-in on a test stand or aircraft per the manual, checking oil pressure/temperature, compression, magneto timing, and for leaks. Overhaul generates extensive documentation: yellow tags on parts, logbook entries, and (for a certified/documented overhaul) an FAA Form 8130-3 or equivalent."},
      {"heading": "Cylinder and Case Inspection at Overhaul", "body": "At overhaul, cylinders are bore-gauged for wear/taper/out-of-round against service limits, and checked for glazing or scoring on the cylinder wall that would prevent proper ring seating. Crankcase halves are checked for fretting at the parting surface and crack-inspected (often by dye penetrant or magnetic particle depending on material) before reassembly. Any crankshaft is checked for straightness (runout) and journal wear, since a bent or worn crankshaft can cause vibration and premature bearing failure even after an otherwise thorough overhaul."},
      {"heading": "Break-In Procedure After Overhaul", "body": "A freshly overhauled reciprocating engine requires a specific break-in procedure (often higher power settings for a defined period, avoiding prolonged idle/low power which can prevent proper ring seating) to allow new rings to properly seat against the cylinder walls. Using a non-detergent break-in oil for the initial break-in period, then switching to normal service oil after the specified time/hours, is a common requirement - straying from this procedure (e.g., babying a new engine at low power out of caution) can actually cause poor ring seating and elevated oil consumption for the engine's service life."}
    , {"heading": "Crankshaft and Camshaft Inspection at Overhaul", "body": "Crankshaft inspection during overhaul includes magnetic particle inspection for cracks (since crankshafts are highly stressed rotating components where a crack can lead to catastrophic failure), journal diameter measurement against wear limits, and runout checking to verify the crankshaft has not developed a bend from operational stress or a previous prop strike event. Camshaft inspection focuses on lobe wear and pitting, since worn or pitted cam lobes alter valve timing and lift, causing power loss and increased wear on associated valve train components even though the engine may still run. Any crankshaft that has been in an aircraft involved in a sudden stoppage event (prop strike) requires disassembly and inspection per the engine manufacturer's specific sudden stoppage inspection procedure, since internal crankshaft damage from a prop strike is often not visible externally but can lead to in-flight failure if not properly inspected and, if necessary, replaced."},
    {"heading": "Valve and Valve Guide Reconditioning at Overhaul", "body": "Exhaust and intake valves are inspected at overhaul for stem wear, face pitting, warpage, and margin thickness, since a valve with insufficient remaining margin after refacing is prone to burning through in service. Valve guides are measured for bore wear and clearance to the valve stem; excessive guide clearance allows the valve to rock in the guide, causing uneven seating, accelerated seat wear, and potential guttering (burning) of the valve face from combustion gas leakage past a poorly seated valve. Reconditioning typically involves reaming or replacing worn guides to restore proper stem clearance, then lapping or grinding valve seats to the specified width and concentricity, and every valve job concludes with a seat leak check (using solvent, air pressure, or dye) to confirm a gas-tight seal before the cylinder is returned to service."},
    {"heading": "Piston Pin and Piston-to-Cylinder Fit Measurement", "body": "Piston pins (wrist pins) are measured for diameter and checked for fit within the piston pin bore and connecting rod bushing, since excessive pin-to-bore clearance allows piston rock/slap during operation, producing a characteristic knocking noise and accelerated wear at the pin bosses, while insufficient clearance can bind and score the pin during thermal expansion at operating temperature. Piston-to-cylinder wall clearance is similarly measured (often by comparing piston skirt diameter to cylinder bore diameter at specified points), since correct clearance allows for thermal expansion of the piston at operating temperature without excessive blow-by (too much clearance) or the risk of the piston seizing in the bore (too little clearance) as the aluminum piston expands more than the steel or nickel-plated cylinder barrel with heat. Overhaul manuals specify these clearances precisely because piston and cylinder materials have different thermal expansion rates, meaning a clearance measured correctly at room temperature is specifically calculated to become the correct operating clearance once the engine reaches normal operating temperature, not simply the tightest fit that seems reasonable when cold."},
    {"heading": "Connecting Rod Inspection and Bearing Clearance Measurement at Overhaul", "body": "Connecting rods undergo thorough inspection at overhaul including magnetic particle or other approved nondestructive inspection for cracks, particularly at the fillet radii and bolt hole areas where stress concentrates, since a cracked connecting rod that fails in service can cause catastrophic engine damage as the rod exits the crankcase. Rod bolt condition and torque history are scrutinized closely, and most manufacturers specify that connecting rod bolts are replaced with new bolts at every overhaul regardless of their apparent visual condition, since these bolts experience cyclic loading that can initiate fatigue cracking not visible to inspection, and the cost of a new bolt is trivial compared to the consequence of a bolt failure in service. Bearing clearance, the small gap between the rod bearing insert and the crankshaft journal, is measured using a plastic deformable gauging material compressed between the bearing and journal during a controlled temporary reassembly, then measuring the flattened width against a calibrated scale to determine clearance, or alternatively by precision measurement of bearing insert thickness and journal diameter and calculating clearance mathematically. Clearance that is too tight can lead to inadequate oil film thickness and bearing overheating or seizure, while clearance that is too loose can cause excessive oil throw-off, reduced oil pressure, and eventual bearing failure from inadequate load support, so the measured clearance must fall within the specific tolerance range published for that engine model and bearing size. Rod alignment, meaning that the rod is not twisted or bent from its original straight configuration, is checked using a rod alignment fixture, since a bent or twisted rod causes uneven piston loading against the cylinder wall that accelerates ring and cylinder wear even if the rod's bearing surfaces and bolts are otherwise in perfect condition."},
    {"heading": "Engine Overhaul Documentation Requirements and Logbook Entry Standards", "body": "Comprehensive documentation is a mandatory component of engine overhaul, establishing an auditable record of the work performed, parts replaced, and measurements taken throughout the disassembly, inspection, reassembly, and test run process. Overhaul records must include reference to the specific overhaul manual and revision used, dimensional inspection data for critical components compared against serviceable limits, a complete parts list identifying which components were reused, repaired, or replaced with new or overhauled parts, and run-in test data confirming the engine met performance acceptance criteria. Logbook entries following overhaul must clearly state the work performed, reference applicable Airworthiness Directives complied with during the overhaul, and be signed and dated by the certificated individual who performed or supervised the work, along with their certificate number. Complete and accurate overhaul documentation is essential not only for regulatory compliance but also for establishing the engine's overhaul time baseline for future maintenance planning, and incomplete records can create significant airworthiness determination difficulties for the engine's subsequent operational history."}],
    "quiz": [ {"q": "Why can a crankshaft that passes magnetic particle crack inspection still be rejected during overhaul?", "choices": ["Crack inspection is the only criterion that matters for crankshaft acceptance", "The crankshaft can still be rejected for excessive runout (bend), journal wear beyond regrind limits, or other dimensional non-conformance", "Crankshafts are never rejected once they pass any single inspection", "Runout and journal wear are not checked during overhaul"], "answer": 1}, {"q": "Why does a crankshaft from an engine that experienced a sudden stoppage (prop strike) require special inspection?", "choices": ["Prop strikes never affect the crankshaft", "Internal crankshaft damage from a prop strike is often not visible externally but can cause in-flight failure", "Only external inspection is ever needed after prop strikes", "Sudden stoppage events only affect the propeller, not the engine"], "answer": 1, "explain": "Prop strikes can cause internal crankshaft damage that is not visible from the outside, requiring the manufacturer's specific sudden stoppage inspection procedure to catch damage that could otherwise lead to failure."},
      {"q": "Why might running a freshly overhauled engine at prolonged low power/idle during break-in actually cause problems?", "choices": ["Low power is always the safest choice for a new engine", "It can prevent proper ring seating, leading to elevated oil consumption for the engine's service life", "It has no effect on ring seating", "New engines don't require any specific break-in procedure"], "answer": 1, "explain": "Prolonged low-power operation during break-in can prevent new rings from properly seating against the cylinder walls, leading to elevated oil consumption for the life of the engine."},
      {"q": "Checking a crankshaft for straightness during overhaul is done primarily to detect:", "choices": ["Paint condition", "Runout (bending) that would cause vibration and premature bearing failure", "Fuel contamination", "Spark plug fouling"], "answer": 1, "explain": "A bent crankshaft (excessive runout) causes vibration and accelerates bearing wear even if all other components are within limits."},
      {"q": "What does TBO stand for?", "choices": ["Total Bearing Output","Time Between Overhaul","Torque Balance Operation","Turbine Bypass Order"], "answer": 1, "explain": "TBO (Time Between Overhaul) is the manufacturer-recommended operating time before overhaul."},
      {"q": "Under Part 91 operations, TBO is generally treated as:", "choices": ["Mandatory in all cases","A recommendation, not mandatory (unless required by an approved program)", "Illegal to exceed", "Only applicable to turbine engines"], "answer": 1, "explain": "For most Part 91 operators, TBO is a manufacturer recommendation rather than a hard regulatory limit."},
      {"q": "Which event would typically require an overhaul sooner than scheduled TBO?", "choices": ["Routine oil change","Sudden stoppage or prop strike","Normal landing","Scheduled inspection"], "answer": 1, "explain": "Sudden stoppage, prop strikes, over-temp events, or metal in the oil are qualifying events that can force an early overhaul."},
      {"q": "Why is a specific break-in procedure needed for new rings/cylinders?", "choices": ['It is optional and rarely followed', 'To properly seat the rings against cylinder walls, preventing glazing and excess oil consumption', 'To test the paint finish', 'To calibrate the propeller'], "answer": 1, "explain": "Proper break-in seats new rings correctly; skipping it can cause glazed cylinder walls and lifelong excess oil consumption."},
      {"q": "What is checked during the post-overhaul run-in?", "choices": ["Only visual paint quality","Oil pressure/temperature, compression, magneto timing, and leaks", "Cabin pressurization", "Passenger seat belts"], "answer": 1, "explain": "The run-in verifies multiple operating parameters and checks for leaks before the engine is returned to service."},
    {"q": "Why does excessive valve guide clearance lead to accelerated valve seat wear and potential valve face guttering?", "choices": ["Guide clearance has no effect on valve seating", "Excessive clearance allows the valve to rock in the guide, causing uneven seating and combustion gas leakage past the seat", "It only affects oil consumption, not valve seating", "Valve guides are not related to valve seat function"], "answer": 1},
    {"q": "Why is piston-to-cylinder wall clearance measured at room temperature specified to a precise value rather than simply fitted as tightly as reasonable?", "choices": ["Room temperature clearance has no relationship to operating temperature clearance", "Piston and cylinder materials expand at different rates with heat, so the cold clearance is specifically calculated to become correct once the engine reaches operating temperature", "Clearance specifications are arbitrary and do not account for thermal expansion", "Pistons and cylinders are always made of identical materials with matched expansion rates"], "answer": 1},
    {"q": "Why do most manufacturers require connecting rod bolts to be replaced with new bolts at every overhaul regardless of visual condition?", "choices": ["Cyclic loading can initiate fatigue cracking not visible to inspection, and bolt failure risk far outweighs the low cost of a new bolt", "Used rod bolts are always visibly damaged and easy to identify", "New bolts are required only for cosmetic reasons during overhaul", "Rod bolts never experience fatigue loading during normal engine operation"], "answer": 0},
    {"q": "What is one critical piece of information that must be included in engine overhaul logbook documentation?", "choices": ["The technician's personal opinion of the engine's paint color", "Reference to the overhaul manual used, dimensional inspection data, parts disposition, and certification with certificate number", "Only the date of overhaul with no other details", "The engine's original purchase price"], "answer": 1}
    ]
  },
  {
    "id": "turbine_overhaul", "title": "Turbine Engine Overhaul & Module Repair", "track": "powerplant", "icon": "&#x1F6E9;",
    "sections": [
      {"heading": "Modular Construction", "body": "Modern turbine engines are built in <b>modules</b> (e.g., fan, compressor, combustor, turbine sections) that can be removed and replaced independently. This modular approach allows a single failed module to be repaired or replaced without a full engine teardown, reducing cost and turnaround time."},
      {"heading": "On-Condition & Life-Limited Parts", "body": "Turbine engines are largely maintained <b>on-condition</b> (via borescope inspection, oil analysis, trend monitoring) rather than a fixed overhaul interval, but certain <b>life-limited parts</b> (LLPs) - typically rotating parts like disks and shafts - have hard cyclic or hourly limits regardless of condition, driven by fatigue life analysis."},
      {"heading": "Borescope Inspection", "body": "A <b>borescope</b> is inserted through access ports to visually inspect internal turbine/compressor blades, combustor liners, and other hot-section components without disassembly. Findings (cracks, erosion, foreign object damage, coating loss) are compared against manufacturer serviceable limits to decide on continued operation, repair, or module removal."},
      {"heading": "Hot Section & Repair Considerations", "body": "The <b>hot section</b> (combustor, turbine) experiences the most severe thermal stress and typically drives overhaul/inspection intervals. Repairs may include blade weld/braze repair, recoating (thermal barrier coatings), and balance checks after any rotor work - imbalance in a high-speed turbine rotor can cause severe vibration and premature bearing wear."},
      {"heading": "Module-Level Overhaul Strategy", "body": "Modern turbine engines are typically overhauled at the module level (fan, compressor, combustor, turbine sections) rather than as a complete engine teardown, allowing a module with life remaining to stay in service while a limiting module is overhauled or replaced separately. Life-limited parts (LLPs) such as disks and shafts have hard cycle limits regardless of condition and must be removed at that limit even if they appear serviceable - condition-based overhaul applies to many other parts, but LLPs are calendar/cycle-driven by design margin, not visible wear."},
      {"heading": "Repair vs. Replace Economic Analysis", "body": "During overhaul, many components fall into a gray zone where repair is technically possible but the repair cost approaches or exceeds new/exchange part cost - overhaul shops perform a repair-vs-replace analysis considering repair cost, remaining service life after repair versus a new part, and turnaround time, not simply defaulting to 'repair if technically feasible.' A part repaired multiple times may also carry cumulative repair history that affects its resale/exchange value or future overhaul options, a consideration beyond the immediate repair decision."}
    , {"heading": "Hot Section Coating Inspection and Restoration", "body": "Turbine and combustor hot section components rely on thermal barrier coatings and oxidation-resistant coatings to survive extreme operating temperatures, and these coatings gradually degrade through spallation (flaking), erosion, and thermal cycling fatigue over operating life, reducing the component's ability to withstand heat and increasing susceptibility to base metal damage. Coating inspection during overhaul uses visual examination under magnification and sometimes fluorescent penetrant methods to detect coating loss areas, and components with coating loss beyond allowable limits require recoating (using thermal spray or other approved processes) or replacement rather than being returned to service with degraded coating. Recoating processes must be performed by appropriately certified repair facilities following the exact process specification, since improper coating application can create adhesion problems that cause the new coating to fail even faster than the original coating did."},
    {"heading": "Turbine Blade Creep and Life-Limiting Damage Mechanisms", "body": "Turbine blades operate at extreme temperatures under continuous centrifugal load, making them susceptible to creep, the slow, permanent elongation of the blade material over time under sustained stress and heat, which is why turbine blades are life-limited parts tracked by cycle count and/or hours rather than inspected purely on-condition. Creep is compounded by thermal fatigue from repeated heating/cooling cycles during start-stop operation, which can initiate cracking at stress concentration points such as cooling holes or the blade root fillet. Because creep and thermal fatigue damage accumulate gradually and are not always visible externally, blade life limits are established through extensive testing and are enforced strictly regardless of the blade's visual condition; a blade that looks pristine at borescope inspection must still be removed at its mandatory life limit because the damage mechanism is metallurgical, not surface-visible."},
    {"heading": "Turbine Disk and Blade Balancing Procedures", "body": "Rotating turbine assemblies must be precisely balanced to prevent excessive vibration that accelerates bearing wear, causes fatigue cracking, and degrades ride quality and instrument readings. Individual turbine blades are matched by weight into sets during manufacture and overhaul, since even small weight variations distributed around the disk create an out-of-balance condition. During assembly, blades are installed following a moment-weight distribution sequence specified by the manufacturer to keep the resultant imbalance within limits, and disks may require static balancing using removable balance weights fitted to designated balance rings or bolt bosses. After assembly, complete rotor stacks (compressor and turbine sections joined by the shaft) undergo dynamic balancing on precision balancing equipment that spins the assembly and measures both the magnitude and angular location of residual imbalance, allowing technicians to add or relocate trim balance weights until the imbalance falls within the specified limit, often expressed in gram-inches or gram-millimeters. Field balancing using trim weights on the fan or accessible rotor can also correct vibration detected in service without full engine teardown, using vibration monitoring equipment to determine the required weight and installation angle."},
    {"heading": "Turbine Disk Cyclic Fatigue Life Tracking and Retirement-for-Cause Methodology", "body": "Turbine disks are classified as life-limited parts subject to low-cycle fatigue from the repeated stress of each engine start and power cycle, and traditionally these parts were mandatorily retired from service after accumulating a fixed number of cycles established through testing and analysis with substantial safety margin, regardless of the individual part's actual condition at that cycle count. Retirement-for-cause is an alternative life management methodology that instead uses advanced nondestructive inspection, such as high-resolution eddy current or fluorescent penetrant inspection capable of detecting flaws far smaller than could previously be found, to evaluate each individual disk's actual condition at intervals, allowing disks that show no detectable flaws to remain in service beyond what a fixed conservative life limit would have allowed, while disks that develop a detectable flaw are removed based on actual condition rather than accumulated cycles alone. This approach requires probabilistic fracture mechanics analysis establishing how quickly a flaw of the smallest reliably detectable size could grow to critical size under the disk's specific stress and cycle profile, which then determines the required inspection interval to ensure any growing flaw would be detected with high confidence before reaching a dangerous size. Accurate cycle counting for each individual disk is essential to either life management approach, and disks are tracked by serial number throughout their service life across potentially multiple engines and operators, with cycle counts and inspection results transferred with the part whenever it moves to a different engine, making disk records among the most rigorously controlled documentation in turbine engine maintenance. Any gap or inconsistency discovered in a disk's cycle history requires conservative resolution, typically by accepting the highest plausible cycle count consistent with the available records, since underestimating actual cycles accumulated would undermine the entire fatigue life management approach's safety basis."},
    {"heading": "Turbine Blade Nondestructive Inspection Methods at Overhaul", "body": "Turbine blades removed during engine overhaul undergo rigorous nondestructive inspection to detect cracks, erosion, and thermal damage that may not be visible during in-service borescope inspection due to limited access and lighting. Fluorescent penetrant inspection is commonly used to detect surface-breaking cracks on blade surfaces, requiring thorough cleaning of the blade to remove combustion deposits and thermal barrier coating residue that could mask indications or produce false positives. Eddy current inspection provides a complementary method capable of detecting subsurface cracking near the blade root and dovetail attachment area, a location subject to high cyclic stress where fatigue cracks commonly initiate. Blade dimensional inspection, comparing measured airfoil twist, thickness, and length against original manufacturing tolerances, identifies blades that have crept or eroded beyond serviceable limits even without visible cracking. The combination of these inspection methods at overhaul provides a comprehensive assessment that in-service inspection alone cannot achieve, which is a key reason why overhaul intervals for hot-section components are typically shorter than for cooler engine sections."}],
    "quiz": [ {"q": "What is the purpose of recoating turbine hot section components during overhaul rather than always replacing them?", "choices": ["Recoating is required by regulation for all components regardless of condition", "Recoating restores thermal protection on components with coating degradation but otherwise sound base metal, avoiding the cost of full replacement", "Coatings never degrade so recoating is unnecessary", "Recoating is purely cosmetic and has no functional purpose"], "answer": 1}, {"q": "What happens to thermal barrier and oxidation-resistant coatings on hot section components over operating life?", "choices": ["They never degrade under any conditions", "They gradually degrade through spallation, erosion, and thermal cycling fatigue", "They only degrade during engine shutdown", "They improve in effectiveness over time"], "answer": 1, "explain": "Hot section coatings degrade over time through flaking (spallation), erosion, and fatigue from repeated thermal cycling, reducing their protective capability."},
      {"q": "During overhaul, why might a shop choose to replace a component with a new/exchange part rather than repair it, even if repair is technically feasible?", "choices": ["Repair is always cheaper regardless of other factors", "The repair cost, remaining service life, and turnaround time may favor replacement in an economic analysis", "Technical feasibility is the only consideration", "Replacement is never considered during overhaul"], "answer": 1, "explain": "Overhaul shops weigh repair cost, resulting service life, and turnaround time against new/exchange part costs, not just technical repair feasibility alone."},
      {"q": "A life-limited part (LLP) in a turbine engine must be removed from service:", "choices": ["Only if visibly worn", "At its specified cycle/hour limit regardless of apparent condition", "Never, they last forever", "Only during a full engine teardown"], "answer": 1, "explain": "LLPs have hard cycle/hour limits based on fatigue design margins and must be removed at that limit even if they look serviceable."},
      {"q": "What is the main advantage of modular turbine engine construction?", "choices": ["Lower initial purchase cost only","A failed module can be repaired/replaced without a full engine teardown","It eliminates the need for inspections","It only applies to piston engines"], "answer": 1, "explain": "Modular construction lets technicians address a specific section without disassembling the entire engine."},
      {"q": "What best describes 'on-condition' maintenance for turbine engines?", "choices": ["Replacing parts at a fixed hourly interval regardless of condition","Maintaining based on inspection findings and trend monitoring rather than a fixed overhaul interval","Never inspecting the engine","Only applicable to piston engines"], "answer": 1, "explain": "On-condition maintenance relies on borescope inspection, oil analysis, and trend monitoring rather than a hard TBO."},
      {"q": "Life-limited parts (LLPs) are typically:", "choices": ["Any part on the engine","Rotating parts like disks/shafts with hard cyclic or hourly limits based on fatigue analysis","Only external cowling parts","Never replaced"], "answer": 1, "explain": "LLPs are usually rotating components with strict cyclic/hourly limits driven by fatigue life analysis, regardless of condition."},
      {"q": "What is a borescope used for?", "choices": ["Measuring fuel flow","Visually inspecting internal engine components through access ports without disassembly","Balancing propellers","Testing electrical continuity"], "answer": 1, "explain": "A borescope allows internal visual inspection of blades, liners, and hot-section parts without opening up the engine."},
      {"q": "Why is a balance check important after rotor blade repair work?", "choices": ["It is not important","Imbalance in a high-speed rotor can cause severe vibration and premature bearing wear","It only affects paint appearance","It only matters for piston engines"], "answer": 1, "explain": "Even small imbalance in a high-speed turbine rotor can cause vibration and accelerate bearing wear/failure."},
    {"q": "Why are turbine blades removed at a mandatory life limit even if they appear visually pristine during borescope inspection?", "choices": ["Visual inspection is always sufficient to detect creep and thermal fatigue damage", "Creep and thermal fatigue damage accumulate metallurgically and are not always visible externally, so life limits are enforced regardless of visual condition", "Life limits are arbitrary and not based on any damage mechanism", "Turbine blades have no life-limiting damage mechanisms"], "answer": 1},
    {"q": "Why are turbine blades matched by weight into sets during manufacture and overhaul?", "choices": ["To make the blades easier to identify visually", "To ensure even weight distribution around the disk and minimize rotating imbalance", "Weight has no effect on rotor balance", "To reduce the total number of blades needed"], "answer": 1},
    {"q": "How does retirement-for-cause life management differ from a traditional fixed cycle life limit for turbine disks?", "choices": ["It uses advanced inspection to evaluate each disk's actual condition, allowing flaw-free disks to remain in service beyond a fixed conservative limit while removing disks with detected flaws based on condition", "Retirement-for-cause eliminates the need for any cycle counting on turbine disks", "Fixed cycle life limits are always more permissive than retirement-for-cause methodology", "Retirement-for-cause applies only to disks that have never been inspected"], "answer": 0},
    {"q": "Why is eddy current inspection particularly valuable at the turbine blade root and dovetail attachment area?", "choices": ["It can only inspect blade surface coatings", "It can detect subsurface fatigue cracking at this high-cyclic-stress location where cracks commonly initiate", "It is used exclusively to measure blade weight", "Eddy current cannot be used on turbine blades"], "answer": 1}
    ]
  }
]

EXT9_FLASHCARDS = [
  {"front": "Dirty Dozen (human factors)", "back": "Twelve common human factors behind maintenance errors: fatigue, complacency, distraction, etc."},
  {"front": "SHELL model center", "back": "Liveware (the person) interacting with Software, Hardware, and Environment."},
  {"front": "Duplicate inspection purpose", "back": "A second, independent inspector catches errors the original mechanic may miss."},
  {"front": "Dye penetrant inspection use", "back": "Detects surface-breaking cracks on non-porous materials like aluminum and steel."},
  {"front": "Magnetic particle inspection limitation", "back": "Only works on ferromagnetic materials (e.g., steel) - not aluminum or titanium."},
  {"front": "Eddy current inspection strength", "back": "Detects surface/near-surface flaws, especially around fastener holes."},
  {"front": "Ultrasonic inspection principle", "back": "Sound wave reflections reveal internal/subsurface flaws and thickness loss."},
  {"front": "Anti-ice vs de-ice", "back": "Anti-ice prevents ice formation continuously; de-ice allows some ice then sheds it periodically."},
  {"front": "Pneumatic boot ice removal", "back": "Sequenced inflation/deflation cracks and sheds accumulated ice."},
  {"front": "Ice bridging risk", "back": "Cycling deice boots too early can form an ice shell the boot can no longer break."},
  {"front": "TBO definition", "back": "Time Between Overhaul - manufacturer-recommended hours before engine overhaul."},
  {"front": "Break-in procedure purpose", "back": "Properly seats new rings against cylinder walls, preventing glazing and excess oil use."},
  {"front": "Turbine modular construction benefit", "back": "A failed module can be repaired/replaced without full engine teardown."},
  {"front": "On-condition maintenance", "back": "Maintenance driven by inspection/trend data rather than a fixed overhaul interval."},
  {"front": "Life-limited parts (LLPs)", "back": "Rotating parts like disks/shafts with hard cyclic/hourly limits from fatigue analysis."},
  {"front": "Borescope", "back": "Instrument inserted through access ports to visually inspect internals without disassembly."},
]

EXT9_GLOSSARY = [
  {"term": "Dirty Dozen", "def": "Twelve common human factors linked to maintenance errors, e.g., fatigue, complacency, distraction."},
  {"term": "SHELL Model", "def": "A human factors framework: Software, Hardware, Environment, Liveware (people)."},
  {"term": "Fatigue Risk Management", "def": "Practices (rest periods, workload planning, self-reporting) to reduce fatigue-related error risk."},
  {"term": "Dye Penetrant Inspection", "def": "NDI method revealing surface-breaking cracks in non-porous materials using capillary-drawn dye."},
  {"term": "Magnetic Particle Inspection", "def": "NDI method using magnetized parts and iron particles to reveal cracks in ferromagnetic materials."},
  {"term": "Eddy Current Inspection", "def": "NDI method using induced electrical currents to detect surface/near-surface flaws in conductive material."},
  {"term": "Ultrasonic Inspection", "def": "NDI method using high-frequency sound wave reflections to detect internal or subsurface flaws."},
  {"term": "Anti-Ice System", "def": "A system that continuously prevents ice formation on a protected surface."},
  {"term": "De-Ice System", "def": "A system that allows limited ice accumulation, then periodically removes it."},
  {"term": "Ice Bridging", "def": "A failure mode where deicing boots cycled too early allow an unbroken ice shell to form over them."},
  {"term": "TBO (Time Between Overhaul)", "def": "Manufacturer-recommended operating hours before an engine overhaul is due."},
  {"term": "Break-In Procedure", "def": "A controlled initial operating period after overhaul that properly seats new rings/cylinders."},
  {"term": "Modular Engine Construction", "def": "Turbine engine design built from independently removable/replaceable sections (fan, compressor, combustor, turbine)."},
  {"term": "Life-Limited Part (LLP)", "def": "A part with a hard cyclic/hourly retirement limit based on fatigue life analysis, regardless of condition."},
  {"term": "Borescope", "def": "An optical inspection instrument inserted through small access ports to view internal components."},
]
