"""Wave 12: Oral & Practical (O&P) Exam Prep reference cards.

The FAA A&P certification process has THREE parts: a Written (knowledge) test,
an Oral exam, and a Practical (hands-on) exam, administered by a Designated
Mechanic Examiner (DME). Nearly every commercial test-prep product focuses
exclusively on the written portion. These cards cover what examinees are
actually asked/asked to demonstrate in the Oral & Practical stages, which is
a genuine differentiator vs. write-only competitor products.
"""

EXT23_REFERENCE = [
    {"cat": "Oral & Practical", "title": "The 3 Parts of A&P Certification", "body": "FAA Mechanic Certification = <b>Written</b> (knowledge test, computer-based) + <b>Oral</b> (verbal Q&A with a DME) + <b>Practical</b> (hands-on tasks/projects). All three must be passed; Oral and Practical are typically given together in one session by your DME."},
    {"cat": "Oral & Practical", "title": "What to Bring to Your O&P", "body": "Government photo ID, your Written test <b>Airman Knowledge Test Report</b>, proof of experience (logbooks/training records/certificate of completion), current AC 43.13-1B and applicable ACs, your own toolbox/PPE, and the FAA's current Airman Certification Standards (ACS) for A&P."},
    {"cat": "Oral & Practical", "title": "Oral Exam: Typical Topics", "body": "Expect questions on: regulations (Part 43/65/91), weight & balance calculations, use of maintenance publications/ADs/service bulletins, inspection procedures, materials & hardware identification, and safe practices (FOD, hazmat, lockout/tagout)."},
    {"cat": "Oral & Practical", "title": "Practical Exam: Task Structure", "body": "The DME selects tasks from the ACS Task Tables covering your rating (Airframe/Powerplant/both). Expect to <b>perform</b> a task (e.g., safety-wire a fitting, splice a wire, inspect a component) and <b>talk through</b> your reasoning and reference to approved data as you work."},
    {"cat": "Oral & Practical", "title": "Logbook Entry Requirements", "body": "A proper maintenance record entry needs: description of work performed, date, total aircraft/component time (if applicable), certificate number & type of the person approving the work, and a statement that the work was performed IAW approved data. Missing any element = an unacceptable entry on your practical."},
    {"cat": "Oral & Practical", "title": "Safety Wire Technique (Practical Staple)", "body": "Twist direction resists the fastener loosening. Standard: 6-8 twists per inch for 0.032in wire (adjust for wire diameter). Wire must be in tension, never slack; pigtail bent away from the part, tucked, and cut to ~1/4-1/2in to avoid FOD/injury. This is one of the most commonly assigned practical tasks."},
    {"cat": "Oral & Practical", "title": "Torque Wrench Use (Practical Staple)", "body": "Verify calibration is current before use. Apply torque smoothly in one continuous motion to the specified value (never in short jerks). If using an extension/adapter, calculate the effective torque setting: TW = TE x (L/(L+A)), where L=wrench length, A=adapter length, TE=desired torque at fastener."},
    {"cat": "Oral & Practical", "title": "Wire Splicing / Termination (Practical Staple)", "body": "Strip length must expose only bare conductor (no nicked strands); crimp with the correct die and verify with a pull test; heat-shrink or solder-sleeve for environmental protection where required. Be ready to identify wire gauge (AWG) by table and explain why it was selected for the circuit's current load."},
    {"cat": "Oral & Practical", "title": "Weight & Balance Problem (Oral Staple)", "body": "Be ready to compute new CG after adding/removing/moving weight: New CG = (Old Total Moment +/- Item Moment) / New Total Weight, where Moment = Weight x Arm. Also know how to determine if the resulting CG falls within the aircraft's approved CG envelope from its weight & balance data."},
    {"cat": "Oral & Practical", "title": "Inspection Authorization (IA) Overview", "body": "An IA is an additional privilege (not automatic) added to an A&P certificate after 3+ years of active A&P privileges, allowing the holder to perform/approve annual and progressive inspections and approve major repairs/alterations for return to service. Requires a separate FAA exam."},
    {"cat": "Oral & Practical", "title": "Approved Data: Know Your Sources", "body": "Be ready to name and describe: Type Certificate Data Sheet (TCDS), Airworthiness Directives (ADs), Service Bulletins (advisory unless referenced by an AD), Advisory Circulars like AC 43.13-1B/2B, and the manufacturer's Maintenance/Illustrated Parts Manual. Examiners frequently ask which source governs a given repair."},
    {"cat": "Oral & Practical", "title": "Major vs. Minor Repair/Alteration", "body": "Be ready to explain the distinction per 14 CFR Part 43 Appendix A: major repairs/alterations can affect airworthiness, weight/balance, structural strength, flight characteristics, or other qualities affecting airworthiness, and require FAA Form 337 and IA/FAA sign-off; minor ones do not."},
    {"cat": "Oral & Practical", "title": "PPE & FOD Awareness (Practical Staple)", "body": "Examiners commonly grade shop discipline as part of the task: eye/hearing protection when required, proper tool control (tool accountability/shadow boards), FOD walk habits, and safe handling of hazmat (fuel, hydraulic fluid, battery acid) with correct PPE and disposal procedures."},
    {"cat": "Oral & Practical", "title": "How to Study for the Oral (Not Just the Written)", "body": "The written test rewards memorization; the Oral rewards being able to <b>explain your reasoning out loud</b> and point to the specific approved-data source for your answer. Practice narrating your work process on real tasks (or in front of a mirror) using the ACS Task Tables as your checklist, not just quiz apps."},
    {"cat": "Oral & Practical", "title": "Common First-Time-Fail Reasons", "body": "The most common O&P failure reasons are: incomplete/incorrect logbook entries, inability to cite the approved data source for a decision, unsafe shop practices during the practical task, and inability to explain the 'why' behind a procedure (not just perform it by rote)."},
]

# ---------------------------------------------------------------------------
# Mock Oral Exam question bank: open-response prompts (not multiple-choice)
# styled after what a Designated Mechanic Examiner (DME) actually asks
# during the Oral portion of the A&P certification exam. Self-graded, since
# real oral exams are verbal and can't be auto-scored the way a written
# quiz can.
# ---------------------------------------------------------------------------
EXT23_ORAL = [
    {"cat": "Regulations & Documentation", "prompt": "What are the three parts of the FAA A&P certification process, and who administers the last two?", "answer": "Written (knowledge test), Oral, and Practical exams. The Oral and Practical are administered together by a Designated Mechanic Examiner (DME)."},
    {"cat": "Regulations & Documentation", "prompt": "What documents must you bring to your Oral & Practical exam?", "answer": "Government photo ID, your Airman Knowledge Test Report, proof of experience (logbooks/training records), current AC 43.13-1B/2B and applicable ACs, your own tools/PPE, and the current FAA Airman Certification Standards (ACS)."},
    {"cat": "Regulations & Documentation", "prompt": "What are the required elements of a proper maintenance logbook entry?", "answer": "Description of the work performed, the date, total aircraft/component time (if applicable), the certificate number and type of the person approving the work for return to service, and a statement that the work was performed in accordance with approved data."},
    {"cat": "Hardware & Rigging", "prompt": "Explain how you determine the correct number of safety wire twists per inch and why the twist must stay in tension.", "answer": "Typically 6-8 twists per inch for 0.032in wire (adjust per wire diameter/spec). The wire must stay in tension (never slack) so it actively resists the fastener backing out; a loose wire provides no security."},
    {"cat": "Hardware & Rigging", "prompt": "How do you calculate the correct torque wrench setting when using an extension or adapter?", "answer": "TW = TE x (L / (L+A)), where TE is the torque value specified for the fastener, L is the wrench's effective length, and A is the extension/adapter length. This compensates for the added leverage."},
    {"cat": "Weight & Balance", "prompt": "Walk through how you'd calculate a new aircraft CG after moving a piece of equipment.", "answer": "Compute each item's Moment = Weight x Arm. New CG = (Old Total Moment +/- the moved item's Moment change) / New Total Weight. Then verify the resulting CG falls within the aircraft's approved CG envelope."},
    {"cat": "Regulations & Documentation", "prompt": "What is the difference between a major and a minor repair or alteration, per 14 CFR Part 43 Appendix A?", "answer": "A major repair/alteration can affect airworthiness, weight & balance, structural strength, or flight characteristics, and requires FAA Form 337 with IA/FAA sign-off. A minor repair/alteration does not meet those criteria and doesn't require Form 337."},
    {"cat": "Regulations & Documentation", "prompt": "Name the sources of 'approved data' you'd cite to justify a repair, and explain the difference between a Service Bulletin and an Airworthiness Directive.", "answer": "Type Certificate Data Sheet (TCDS), Airworthiness Directives (ADs), Service Bulletins, Advisory Circulars (e.g. AC 43.13-1B/2B), and the manufacturer's Maintenance/Illustrated Parts Manual. An AD is mandatory/regulatory; a Service Bulletin is advisory unless an AD specifically references and mandates it."},
    {"cat": "Regulations & Documentation", "prompt": "What is an Inspection Authorization (IA), and what are the basic eligibility requirements?", "answer": "An IA is an added privilege on an A&P certificate that allows performing/approving annual and progressive inspections and approving major repairs/alterations for return to service. It requires at least 3 years of active A&P privileges and passing a separate FAA exam."},
    {"cat": "Safety & Shop Practices", "prompt": "What PPE and shop-discipline practices would you demonstrate/explain during a practical task?", "answer": "Appropriate eye/hearing protection, proper tool control and accountability (e.g. shadow boards), FOD awareness/walks, and correct PPE and disposal procedures when handling hazmat like fuel, hydraulic fluid, or battery acid."},
    {"cat": "Electrical", "prompt": "When splicing or terminating a wire, what would you check before crimping, and how would you verify the crimp?", "answer": "Verify the strip length exposes only bare conductor with no nicked strands, use the correct crimp die for the terminal and wire gauge, then verify the crimp with a pull test; apply heat-shrink or solder-sleeve for environmental protection where required."},
    {"cat": "Exam Strategy", "prompt": "Why does an examiner care about your reasoning process, not just whether you get the right final answer?", "answer": "The Oral exam is designed to test judgment and the ability to justify decisions using approved data sources, not rote memorization. Being able to explain 'why' and cite the correct reference is often weighted as heavily as the task outcome itself."},
    {"cat": "Exam Strategy", "prompt": "What are the most common reasons candidates fail the Oral & Practical on their first attempt?", "answer": "Incomplete or incorrect logbook entries, inability to cite the approved data source for a decision, unsafe shop practices during the practical task, and inability to explain the reasoning behind a procedure rather than just performing it by rote."},
    {"cat": "Electrical", "prompt": "How would you identify the correct wire gauge (AWG) for a given circuit, and what would you check for during inspection?", "answer": "Use the aircraft wiring/AWG ampacity tables based on circuit current load and length/voltage drop considerations, then verify no chafing, corrosion, or damaged insulation and that the gauge matches what's specified in the wiring diagram."},
    {"cat": "Regulations & Documentation", "prompt": "If a Designated Mechanic Examiner asks you to justify a repair method, what should your answer always reference?", "answer": "The specific approved data source authorizing that repair method for that aircraft/part -- e.g. the manufacturer's maintenance manual, an AD, a TCDS, or an applicable AC -- not general shop practice alone."},
]

# ---------------------------------------------------------------------------
# Practical Task Log: a hands-on training-record checklist styled after the
# ACS (Airman Certification Standards) Task Tables a DME draws from during
# the Practical exam. Written/oral quiz apps never touch this -- but a real
# A&P candidate's actual experience log of "have I physically practiced this"
# is arguably the single most important prep gap in every competing product.
# ---------------------------------------------------------------------------
EXT23_PRACTICAL = [
    {"id": "pt_safety_wire", "cat": "General", "title": "Safety Wire a Fitting", "desc": "Twist and install safety wire on a bolted fitting with correct tension, twist rate, and pigtail direction."},
    {"id": "pt_torque_wrench", "cat": "General", "title": "Torque a Fastener to Spec", "desc": "Select and apply the correct torque value to a fastener, including an extension/adapter torque calculation."},
    {"id": "pt_wire_splice", "cat": "General", "title": "Splice/Terminate a Wire", "desc": "Strip, crimp, and verify (pull test) a wire termination; apply heat-shrink or solder-sleeve protection."},
    {"id": "pt_logbook_entry", "cat": "General", "title": "Write a Compliant Logbook Entry", "desc": "Draft a maintenance record entry with all required elements: work description, date, time, certificate info, and approved-data statement."},
    {"id": "pt_wb_calc", "cat": "General", "title": "Perform a Weight & Balance Calculation", "desc": "Compute a new CG after a weight change and verify it falls within the approved envelope."},
    {"id": "pt_fod_walk", "cat": "General", "title": "Conduct a FOD Walk / Shop Cleanup", "desc": "Demonstrate FOD awareness and tool-control discipline in a shop environment."},
    {"id": "pt_ad_research", "cat": "General", "title": "Research an Applicable AD/Service Bulletin", "desc": "Look up and correctly interpret an Airworthiness Directive or Service Bulletin applicability for a given aircraft/component."},
    {"id": "pt_corrosion_id", "cat": "Airframe", "title": "Identify and Classify Corrosion", "desc": "Inspect a structure/panel and correctly classify corrosion type and severity using approved criteria."},
    {"id": "pt_sheet_metal", "cat": "Airframe", "title": "Layout and Form a Sheet Metal Repair", "desc": "Calculate bend allowance/setback and fabricate a basic sheet-metal patch or doubler."},
    {"id": "pt_fabric_patch", "cat": "Airframe", "title": "Fabric Covering Inspection/Repair", "desc": "Inspect fabric covering condition (e.g. punch test) and demonstrate a basic repair technique."},
    {"id": "pt_landing_gear", "cat": "Airframe", "title": "Inspect Landing Gear & Brake System", "desc": "Perform a landing gear/brake inspection, checking servicing, wear limits, and rigging."},
    {"id": "pt_hydraulic_svc", "cat": "Airframe", "title": "Service a Hydraulic System", "desc": "Check fluid level/type, bleed air, and inspect for leaks on a hydraulic system."},
    {"id": "pt_annual_insp", "cat": "Airframe", "title": "Perform Items from an Annual Inspection Checklist", "desc": "Work through representative items from an annual/100-hr inspection checklist per Part 43 Appendix D."},
    {"id": "pt_engine_insp", "cat": "Powerplant", "title": "Perform a Powerplant Inspection", "desc": "Inspect an engine per its inspection checklist, including accessories, mounts, and controls."},
    {"id": "pt_oil_change", "cat": "Powerplant", "title": "Perform an Oil Change & Filter/Screen Inspection", "desc": "Change engine oil, inspect the filter/screen for contamination, and document the service."},
    {"id": "pt_prop_insp", "cat": "Powerplant", "title": "Inspect a Propeller", "desc": "Inspect a propeller for damage, track, and balance per manufacturer criteria."},
    {"id": "pt_mag_timing", "cat": "Powerplant", "title": "Check/Set Magneto Timing", "desc": "Verify and adjust magneto-to-engine timing using proper timing equipment."},
    {"id": "pt_fuel_system", "cat": "Powerplant", "title": "Inspect/Service a Fuel System Component", "desc": "Inspect a carburetor, fuel injection component, or fuel system line/fitting for airworthiness."},
    {"id": "pt_borescope", "cat": "Powerplant", "title": "Perform a Borescope/NDT Inspection", "desc": "Use a borescope or other NDT method to inspect an internal engine component for defects."},
    {"id": "pt_run_up", "cat": "Powerplant", "title": "Conduct an Engine Run-Up/Ground Check", "desc": "Perform a documented engine ground run and record key parameters against limits."},
]
