# -*- coding: utf-8 -*-
"""Aviation Maintenance Academy - Content Expansion Pack 5 (Wave 3)
Adds 5 new modules balanced toward Airframe/Powerplant. Merged in academy_data.py.
"""

EXT5_MODULES = [
  {
    "id": "aerodynamics", "title": "Aerodynamics Fundamentals", "track": "airframe", "icon": "&#x1FA82;",
    "sections": [
      {"heading": "Four Forces of Flight", "body": "<b>Lift</b> (up, from the wing), <b>Weight</b> (down, gravity), <b>Thrust</b> (forward, powerplant), <b>Drag</b> (rearward, resistance). Steady, level, unaccelerated flight requires Lift=Weight and Thrust=Drag."},
      {"heading": "Lift Generation", "body": "Airfoil shape + angle of attack (AOA) accelerate air over the upper surface, lowering pressure (Bernoulli) while also deflecting airflow downward (Newton's 3rd law reaction). Lift increases with AOA up to the <b>critical angle of attack</b>, beyond which the wing stalls."},
      {"heading": "Drag Types", "body": "<b>Parasite drag</b> (form, skin friction, interference) increases with speed squared. <b>Induced drag</b> (from wingtip vortices/lift generation) decreases with speed. Total drag is lowest at <b>L/D max</b> speed - best glide/range speed."},
      {"heading": "Stalls & Load Factor", "body": "A stall is a critical-AOA event, not simply a low-airspeed event - it can happen at any airspeed with enough AOA (e.g., a steep turn). <b>Load factor</b> (G) increases stall speed: Stall speed increases with the square root of load factor. Steeper banks and turbulence increase load factor and stall risk."},
      {"heading": "Stability & Control", "body": "<b>Longitudinal stability</b> (pitch) depends on CG location relative to the wing's center of lift and horizontal stabilizer effect. <b>Lateral</b> (roll, ailerons/dihedral) and <b>directional</b> (yaw, rudder/vertical fin) stability keep the aircraft tracking predictably. A mechanic's rigging work directly affects all three."},
      {"heading": "Stall Recognition and Recovery Basics", "body": "A stall occurs when the wing exceeds its critical angle of attack, not necessarily at any specific airspeed - a wing can stall at high speed during a steep turn or low-speed climb, since angle of attack (not airspeed alone) is the determining factor. As a mechanic, understanding this matters for evaluating stall-warning system function (angle-of-attack vane calibration and rigging) and for correctly interpreting flight-test or squawk reports that mention 'stall buffet' or 'stall warning activation' during otherwise normal-seeming airspeeds."}
    , {"heading": "Ground Effect and Its Influence on Flight", "body": "Ground effect occurs when an aircraft flies within roughly one wingspan of the surface, reducing induced drag because the ground interferes with the formation of wingtip vortices and downwash. This produces the sensation of the aircraft \"floating\" during landing flare or requiring extra distance to become airborne during takeoff, since the reduced drag lets the aircraft accelerate more easily near the ground but also makes it harder to descend through if approach speed is too high. Pilots and mechanics evaluating unusual takeoff or landing performance complaints should consider ground effect interactions with density altitude and weight, since all three compound during hot, high-elevation operations."}, {"heading": "Adverse Yaw and the Need for Coordinated Rudder Use", "body": "Adverse yaw occurs during a banking turn when the aileron on the rising wing produces more induced drag than the aileron on the descending wing, causing the aircraft's nose to yaw momentarily away from the direction of the intended turn unless corrected with coordinated rudder input. This effect happens because the downward-deflected aileron on the rising wing generates more lift and thus more induced drag than the upward-deflected aileron on the falling wing, creating an asymmetric drag condition despite both ailerons being commanded through the same control input. Pilots learn to counter adverse yaw with coordinated rudder application in the direction of the turn, and aircraft design features like differential ailerons (which deflect the down-going aileron less than the up-going aileron) or frise-type ailerons (which expose the leading edge of the up-going aileron into the airstream to add drag on that side) are engineered specifically to reduce the magnitude of adverse yaw and lessen the rudder correction required. Mechanics rigging aileron systems must maintain the correct differential deflection ratios specified by the manufacturer, since incorrect rigging that eliminates or exaggerates the intended aileron differential can alter the aircraft's adverse yaw characteristics from what pilots are trained to expect."},
    {"heading": "Wingtip Vortices and Wake Turbulence Hazard", "body": "Wingtip vortices form because high-pressure air beneath the wing spills around the wingtip toward the lower-pressure air above it, creating a rotating vortex trailing behind each wingtip; these vortices are strongest when a wing is producing the most lift relative to its speed, meaning wake turbulence hazard is greatest during takeoff, climb, and landing at low speed and high angle of attack, particularly behind large, heavy, slow aircraft. An aircraft encountering another's wake vortex can experience a severe, uncommandable rolling moment if it enters the vortex core, which is why air traffic control applies wake turbulence separation standards behind heavier aircraft categories, and why pilots are trained to fly above and upwind of a preceding aircraft's flight path when able. Vortices sink slowly and drift with the wind, persisting for a minute or more depending on atmospheric conditions, so the hazard can remain even after the generating aircraft has passed some distance away."}],
    "quiz": [ {"q": "What causes adverse yaw during a banking turn using ailerons?", "choices": ["The rudder is deflected in the wrong direction", "The downward-deflected aileron on the rising wing generates more induced drag than the upward-deflected aileron on the falling wing", "Adverse yaw only occurs during level flight", "Aileron deflection has no effect on drag distribution"], "answer": 1}, {"q": "What causes the reduced induced drag experienced in ground effect?", "choices": ["Increased air density near the ground", "Interference with wingtip vortex and downwash formation near the surface", "Higher engine power near the ground", "Reduced angle of attack automatically"], "answer": 1, "explain": "Ground effect reduces induced drag because the nearby surface disrupts the normal formation of wingtip vortices and downwash."},
      {"q": "A wing stalls when it exceeds its critical angle of attack, which means:", "choices": ["Stalls only happen at a fixed low airspeed", "A wing can stall at high speed too if the angle of attack is exceeded, such as in a steep turn", "Stalls are unrelated to angle of attack", "Only slow aircraft can stall"], "answer": 1, "explain": "Angle of attack, not airspeed alone, determines a stall - a wing can exceed its critical angle of attack at higher speeds during maneuvers like steep turns."},
      {"q": "In steady, level, unaccelerated flight:", "choices": ["Lift > Weight and Thrust > Drag", "Lift = Weight and Thrust = Drag", "Only thrust matters", "Weight must exceed lift"], "answer": 1, "explain": "Steady level flight requires the four forces to balance: Lift equals Weight, Thrust equals Drag."},
      {"q": "A wing stalls when it exceeds:", "choices": ["A specific airspeed only", "The critical angle of attack", "Maximum RPM", "The service ceiling"], "answer": 1, "explain": "A stall is fundamentally an AOA event - it can occur at any airspeed if the critical angle of attack is exceeded."},
      {"q": "Induced drag behaves as speed increases:", "choices": ["It increases with speed", "It decreases with speed", "It's unaffected by speed", "It only exists at high speed"], "answer": 1, "explain": "Induced drag (from lift generation/wingtip vortices) decreases as airspeed increases, opposite of parasite drag."},
      {"q": "Increasing load factor (G) in a steep turn does what to stall speed?", "choices": ["Decreases it", "Increases it (with the square root of load factor)", "Has no effect", "Only affects turbine aircraft"], "answer": 1, "explain": "Stall speed increases with the square root of load factor - a 2G turn raises stall speed by about 41%."},
      {"q": "Longitudinal stability is most directly affected by:", "choices": ["Rudder trim only", "CG location relative to the wing's center of lift", "Tire pressure", "Paint scheme"], "answer": 1, "explain": "CG position relative to the center of lift (plus horizontal stabilizer effect) governs pitch/longitudinal stability - a mechanic's W&B work matters here."},
    {"q": "During which phase of flight are wingtip vortex wake turbulence hazards typically strongest?", "choices": ["High-speed cruise at high altitude", "Takeoff, climb, and landing, when a wing produces the most lift relative to its speed at high angle of attack", "During descent with flaps and gear retracted", "Wake turbulence intensity is constant regardless of flight phase"], "answer": 1}
    ]
  },
  {
    "id": "environmental_oxygen", "title": "Environmental & Oxygen Systems", "track": "airframe", "icon": "&#x1F6C1;",
    "sections": [
      {"heading": "Cabin Pressurization", "body": "Pressurized aircraft maintain a lower <b>cabin altitude</b> than actual flight altitude using bleed air and outflow valves. <b>Pressure differential</b> (cabin minus ambient) is limited by structural design - exceeding it risks structural damage; a <b>pressure relief valve</b> protects against overpressurization."},
      {"heading": "Environmental Control System (ECS)", "body": "Bleed air (turbine) or engine-driven compressors cool/heat and condition cabin air via <b>packs</b ) (air cycle machines) or vapor-cycle systems. Includes temperature control, humidity/moisture management, and air distribution/mixing valves."},
      {"heading": "Supplemental Oxygen", "body": "Required above certain cabin altitudes per regulation (crew/passenger requirements differ by altitude and duration). Systems: <b>gaseous</b> (high-pressure cylinders, most common), <b>chemical generators</b> (single-use, passenger drop-down masks), <b>liquid oxygen (LOX)</b> (less common, high-density storage)."},
      {"heading": "Oxygen System Safety", "body": "High-pressure oxygen + any hydrocarbon (oil, grease) = explosion risk - use only oxygen-approved lubricants/cleaning agents. Servicing requires slow fill to avoid adiabatic heating. Leak checks use approved leak-detection compound (never soap that could contain oil)."},
      {"heading": "Oxygen System Servicing Precautions", "body": "Oxygen systems demand scrupulous cleanliness - oil, grease, or hydraulic fluid contacting high-pressure oxygen can ignite violently. Only oxygen-clean tools and components rated for oxygen service may be used, fittings are torqued per the AMM (never over-tightened), and servicing carts are bonded/grounded before connecting. Slowly crack open valves to avoid rapid compression heating (adiabatic heating) inside the line, which can ignite trace contamination. No smoking, open flame, or unauthorized electrical equipment near oxygen servicing."},
      {"heading": "Cabin Altitude and Oxygen Requirement Thresholds", "body": "FAA regulations specify supplemental oxygen requirements based on cabin altitude and duration - crew members typically need oxygen above 12,500 ft cabin altitude for extended time and above 14,000 ft continuously, while passengers need it made available above 15,000 ft. As a mechanic, understanding these thresholds matters when troubleshooting an oxygen system discrepancy or evaluating whether a pressurization fault (causing higher-than-normal cabin altitude) creates an airworthiness issue requiring oxygen system backup verification before further dispatch."}
    , {"heading": "Oxygen Mask and Regulator Testing Procedures", "body": "Crew and passenger oxygen masks and regulators must be functionally tested to verify proper flow rate and mask seal integrity, since a mask with degraded elastic straps or a cracked seal may show adequate flow on a bench test but fail to deliver adequate oxygen concentration to the wearer's face in actual use. Diluter-demand regulators, common in crew oxygen systems, blend cabin air with pure oxygen based on cabin altitude to conserve the oxygen supply, and their function must be verified across the altitude range they are designed to compensate for, not just at a single test point. Chemical oxygen generators used in passenger drop-down mask systems produce oxygen through an exothermic chemical reaction when activated and cannot be tested non-destructively, so they are tracked by expiration date and replaced on schedule rather than functionally verified in place."},
    {"heading": "Chemical Oxygen Generator Hazards and Handling Precautions", "body": "Passenger service unit oxygen masks on many transport aircraft are supplied by chemical oxygen generators rather than gaseous cylinders. These generators produce oxygen through an exothermic chemical reaction (typically a sodium chlorate core) once a firing pin is struck by the mask lanyard pull. Because the reaction produces significant heat, expended and unexpended generators are classified as hazardous materials and must never be treated as ordinary scrap: a generator that has been dropped, punctured, or exposed to fire risk must be handled and disposed of per the maintenance manual and applicable hazmat regulations, since a damaged unit can auto-ignite. Technicians must also verify that generator install dates are within the finite shelf life specified by the manufacturer, and that the correct generator part number matches the PSU location, since generators for crew and passenger stations may have different oxygen output durations."},
    {"heading": "ECS Pack Valve and Bleed Air Temperature Control", "body": "Air conditioning packs regulate the temperature of bleed air delivered to the cabin by modulating a pack temperature control valve that blends hot bleed air with air cooled by the pack's heat exchangers and air cycle machine, targeting a temperature commanded by the cabin temperature control system for each zone. A pack valve that sticks or fails to modulate properly can deliver air that is too hot (risking duct overheat protection trips or passenger discomfort) or too cold, and because packs typically operate in parallel supplying a common mixing manifold, a single failed pack valve can sometimes be masked by the other pack compensating, making the fault less obvious until the second pack is also needed at high demand. Pack valve and associated temperature sensor troubleshooting requires checking the valve's actual commanded versus achieved position (often via a position feedback signal) rather than assuming a valve that receives a correct command signal is actually moving to match it."}],
    "quiz": [ {"q": "Why must diluter-demand oxygen regulators be tested across a range of simulated altitudes rather than just at ground level?", "choices": ["Ground-level testing is always sufficient for all regulator types", "A regulator malfunction could provide insufficient oxygen enrichment at high altitude despite functioning normally at ground level", "Altitude has no effect on regulator function", "Testing at altitude is easier to perform"], "answer": 1}, {"q": "Why can't chemical oxygen generators in passenger drop-down masks be functionally tested in place?", "choices": ["They can always be tested without consequence", "They produce oxygen via an exothermic chemical reaction when activated and cannot be tested non-destructively", "They are never actually used in aircraft", "Testing them improves their lifespan"], "answer": 1, "explain": "Chemical oxygen generators react irreversibly once activated, making non-destructive functional testing impossible; they are tracked and replaced by expiration date instead."},
      {"q": "Understanding cabin-altitude oxygen requirement thresholds matters to a mechanic mainly because:", "choices": ["It is irrelevant to maintenance", "It helps assess whether a pressurization fault creates an airworthiness/oxygen-backup issue", "It only matters to pilots", "Cabin altitude has no regulatory oxygen requirements"], "answer": 1, "explain": "A mechanic evaluating a pressurization fault needs to know the regulatory oxygen thresholds to properly assess whether backup oxygen systems must be verified before dispatch."},
      {"q": "Why must oxygen system valves be opened slowly during servicing?", "choices": ["To save oxygen", "Rapid compression can cause adiabatic heating that ignites contamination", "It is faster", "To reduce noise"], "answer": 1, "explain": "Opening an oxygen valve quickly compresses gas rapidly downstream, generating heat (adiabatic heating) that can ignite trace oil/grease contamination."},
      {"q": "Cabin altitude refers to:", "choices": ["The aircraft's actual flight altitude", "The equivalent pressure altitude maintained inside the cabin", "Ground elevation at departure", "Cruise speed"], "answer": 1, "explain": "Pressurization keeps the cabin at a lower equivalent altitude (higher pressure) than the aircraft's actual flight altitude."},
      {"q": "A pressure relief valve on a pressurized cabin protects against:", "choices": ["Underpressurization only", "Structural damage from overpressurization", "Engine overspeed", "Fuel contamination"], "answer": 1, "explain": "The relief valve vents excess pressure to prevent exceeding the structure's designed maximum pressure differential."},
      {"q": "Which oxygen system is most common for gaseous supplemental oxygen?", "choices": ["Chemical generators only", "High-pressure gaseous cylinders", "LOX exclusively", "Compressed nitrogen"], "answer": 1, "explain": "High-pressure gaseous oxygen cylinders are the most widely used supplemental oxygen source in aviation."},
      {"q": "Why must oxygen system components avoid contact with oil/grease?", "choices": ["It stains the fittings", "High-pressure oxygen with hydrocarbons creates an explosion hazard", "It reduces flow rate slightly", "No real hazard exists"], "answer": 1, "explain": "Oxygen combined with hydrocarbon contamination under pressure can ignite explosively - only oxygen-approved lubricants are permitted."},
      {"q": "Slow-filling an oxygen system is important to avoid:", "choices": ["Wasting oxygen", "Adiabatic heating that could ignite contamination or damage components", "Overfilling the gauge", "Freezing the line"], "answer": 1, "explain": "Rapid compression during fast fills generates adiabatic heat, which combined with any contamination is a fire/explosion risk."},
    {"q": "Why must chemical oxygen generators used in passenger service units be handled as hazardous material even when not yet activated?", "choices": ["They are pressurized to over 3000 psi", "The exothermic chemical reaction core can auto-ignite if the unit is damaged, dropped, or punctured", "They contain compressed liquid oxygen", "They require refrigerated storage"], "answer": 1},
    {"q": "Why might a single failed pack temperature control valve go unnoticed for a period of time on a twin-pack ECS system?", "choices": ["Failed pack valves always cause immediate and obvious cabin temperature swings", "The other operating pack can sometimes compensate at the common mixing manifold, masking the fault until higher demand exposes it", "Pack valves have no effect on cabin temperature", "ECS systems only use a single pack, so this scenario cannot occur"], "answer": 1}
    ]
  },
  {
    "id": "turbine_fuel_ignition", "title": "Turbine Fuel & Ignition Systems", "track": "powerplant", "icon": "&#x1F525;",
    "sections": [
      {"heading": "Turbine Fuel Systems", "body": "Fuel flows from tanks through boost pumps, filters, and a <b>fuel control unit (FCU)</b> (hydromechanical or FADEC-electronic) that schedules fuel flow for the requested power setting, altitude, and temperature. <b>Fuel nozzles/atomizers</b> spray fuel into the combustor for efficient burning."},
      {"heading": "FADEC", "body": "<b>Full Authority Digital Engine Control</b> computers manage fuel scheduling, limits (N1/N2/EGT), and protection automatically - reducing pilot workload and protecting the engine from exceedances. Dual-channel redundancy is standard; a channel fault typically reverts to the other channel."},
      {"heading": "Igniters & Ignition Systems", "body": "Turbine engines use high-energy <b>igniter plugs</b> (not spark plugs like reciprocating engines) fired by an ignition exciter, typically only needed for starting and inclement-weather/continuous ignition - combustion is self-sustaining once established."},
      {"heading": "Start Sequence & Faults", "body": "Normal start: starter motor spins N2, igniters fire, fuel introduced, light-off (EGT rise), N1/N2 accelerate to idle. <b>Hot start</b> = EGT exceeds limit. <b>Hung start</b> = light-off but stalls below idle. <b>No start</b> = no light-off (check fuel, ignition, starter air/electrical power)."},
      {"heading": "Hot Start and No-Start Troubleshooting", "body": "A hot start (ITT/EGT exceeding limits during start) is usually caused by excess fuel flow during light-off, a weak igniter delaying combustion, or insufficient starter cranking speed. A no-start with fuel and ignition present but no light-off often points to a fuel nozzle spray pattern problem, an igniter gap that is fouled or worn, or incorrect start-fuel scheduling by the FADEC/fuel control. Any hot start event requires a borescope inspection of the hot section per the engine manual before the next flight."},
      {"heading": "Igniter Plug Inspection", "body": "Turbine igniter plugs are inspected for electrode gap/erosion, carbon buildup, and cracking of the ceramic insulator - an eroded gap beyond limits requires more energy to fire reliably and can cause intermittent hot/no-start issues even when bench-tested as functional under lower-stress conditions. Igniter exciter units store high voltage and must be treated with the same respect as any high-voltage capacitor system: discharge per the maintenance manual procedure before handling, since a stored charge can deliver a dangerous shock even with the aircraft unpowered."}
    , {"heading": "Fuel Nozzle Atomization and Spray Pattern Inspection", "body": "Turbine engine fuel nozzles must atomize fuel into a fine mist with a specific spray pattern (cone angle and distribution) to ensure proper mixing with combustion air and even, complete combustion within the combustor; a degraded nozzle spray pattern from coking (carbon deposit buildup) or physical damage can cause localized hot spots, incomplete combustion, or increased smoke emission. Nozzle flow testing on a test bench verifies both the flow rate at specified pressure and the visual spray pattern quality, with nozzles failing either check requiring cleaning, repair, or replacement before return to service. Uneven fuel distribution among multiple nozzles feeding the same combustor can cause circumferential temperature variation that shows up as an uneven turbine inlet temperature profile, potentially leading to localized hot section damage even though the average temperature reading appears within limits."},
    {"heading": "Fuel Nozzle Coking and Carbon Deposit Formation", "body": "Coking is the formation of hard carbon deposits inside fuel nozzles and injector tips caused by fuel breaking down under high heat when the engine is shut down while nozzle passages are still hot, or from prolonged low-flow/idle operation that allows fuel to linger in heated passages. Coked nozzles produce distorted spray patterns, uneven combustion, localized hot spots on combustor liners, and can eventually block fuel flow entirely to an affected nozzle. Some engines mitigate coking with fuel-cooled oil coolers that keep fuel temperature down, or with a scheduled cool-down/motoring period before shutdown to purge hot fuel from the manifold. Borescope inspection of the combustor and nozzle tips during scheduled checks can reveal early coking before it produces a measurable performance or temperature spread symptom, making it a preventive maintenance item rather than purely a fault-driven repair."}],
    "quiz": [ {"q": "What is a common cause of degraded fuel nozzle spray pattern in a turbine engine, and what problem can result?", "choices": ["Excessive nozzle cooling; causing reduced fuel flow only", "Carbon deposits (coking) from fuel breakdown at high temperatures, which can cause uneven combustion and localized hot-section damage", "Nozzle spray pattern has no effect on engine operation", "Only fuel type affects spray pattern, never nozzle condition"], "answer": 1}, {"q": "What can degraded fuel nozzle spray pattern from coking cause in a turbine combustor?", "choices": ["Improved combustion efficiency", "Localized hot spots, incomplete combustion, or increased smoke emission", "No effect on engine operation", "Automatic nozzle self-cleaning"], "answer": 1, "explain": "A degraded spray pattern from carbon deposit buildup (coking) disrupts proper fuel-air mixing, potentially causing localized hot spots, incomplete combustion, and increased smoke."},
      {"q": "Before handling a turbine ignition exciter unit, a mechanic must:", "choices": ["Immediately touch the terminals", "Discharge the unit per the maintenance manual procedure, since it can retain a dangerous stored charge", "Nothing special is needed", "Only wear gloves"], "answer": 1, "explain": "Ignition exciter units store high voltage internally and must be properly discharged before handling to avoid a dangerous electrical shock, even when the aircraft is unpowered."},
      {"q": "A turbine engine that exceeds ITT limits during start (hot start) requires:", "choices": ["Nothing, it is normal", "A borescope inspection of the hot section before further flight", "Only a logbook note", "Replacing the battery"], "answer": 1, "explain": "A hot start can damage hot-section components; the engine manual requires a borescope inspection before the engine flies again."},
      {"q": "The fuel control unit's (FCU) main job is to:", "choices": ["Cool the fuel", "Schedule fuel flow for the requested power, altitude, and temperature", "Filter oil", "Control landing gear"], "answer": 1, "explain": "The FCU (hydromechanical or FADEC) meters fuel flow appropriately based on power lever position and ambient/engine conditions."},
      {"q": "FADEC stands for:", "choices": ["Fixed Aircraft Data Engine Computer", "Full Authority Digital Engine Control", "Fuel Air Detection Engine Circuit", "Forward Auxiliary Drive Engine Cell"], "answer": 1, "explain": "Full Authority Digital Engine Control - a computer system managing fuel scheduling and engine limit protection."},
      {"q": "Turbine engines use igniter plugs mainly during:", "choices": ["Continuous cruise operation", "Starting and adverse weather/continuous ignition conditions", "Shutdown only", "Taxi only"], "answer": 1, "explain": "Once combustion is established it's self-sustaining; igniters are primarily needed for start and icing/heavy precipitation conditions."},
      {"q": "A 'hung start' is characterized by:", "choices": ["No light-off at all", "Light-off occurs but the engine stalls below idle RPM", "EGT exceeding limits", "Normal acceleration to idle"], "answer": 1, "explain": "A hung start lights off but fails to accelerate to idle - often due to insufficient starter assist or fuel scheduling issue."},
      {"q": "A dual-channel FADEC fault in one channel typically results in:", "choices": ["Complete engine shutdown", "Automatic reversion to the other channel", "No effect on operation logged", "Immediate overspeed"], "answer": 1, "explain": "Redundant dual-channel FADEC design allows the healthy channel to take over if one channel faults, maintaining engine control."},
    {"q": "What operational practice helps prevent fuel nozzle coking on a turbine engine?", "choices": ["Increasing idle time before every shutdown", "A scheduled cool-down/motoring period before shutdown to purge hot fuel from the manifold", "Running the engine at maximum continuous power before shutdown", "Coking cannot be prevented through any operational practice"], "answer": 1}
    ]
  },
  {
    "id": "engine_instruments", "title": "Engine Instruments & Monitoring", "track": "powerplant", "icon": "&#x1F4CA;",
    "sections": [
      {"heading": "Reciprocating Engine Instruments", "body": "<b>Tachometer</b> (RPM), <b>Manifold pressure</b> (power setting on constant-speed-prop aircraft), <b>Oil pressure/temperature</b>, <b>Cylinder head temperature (CHT)</b>, <b>Fuel flow/pressure</b>, <b>EGT</b> for leaning. Each has a green (normal), yellow (caution), red (limit) arc/marking."},
      {"heading": "Turbine Engine Instruments", "body": "<b>N1/N2 (or Ng/Np)</b> - fan/compressor and turbine spool speeds as % of max. <b>EGT/ITT</b> - exhaust/inlet turbine temperature, the key limiting parameter. <b>Torque</b> (turboprops) - actual power output indicator. <b>Fuel flow</b> for engine health/leaning trend monitoring."},
      {"heading": "Engine Trend Monitoring", "body": "Recording EGT, oil temp/pressure, fuel flow, and vibration over time reveals gradual degradation (e.g., rising EGT margin loss signals compressor/turbine wear) before it becomes a failure - a maintenance best practice beyond simple pass/fail checks at each flight."},
      {"heading": "Instrument Power & Failure Modes", "body": "Electronic engine instruments (EIS/glass displays) depend on sensors + processing; a failed sensor can show an erroneous reading rather than obviously failing - cross-check against other parameters. Mechanical gauges (direct-reading, e.g., some oil pressure gauges) are simpler but still need periodic calibration/leak checks."},
      {"heading": "Instrument Discrepancy Troubleshooting", "body": "When an engine instrument reads outside expected range, first rule out the instrument/sender itself before condemning the engine: swap or bench-test the sender/transducer, check wiring continuity and grounds, and compare against a second independent indication if available (e.g., compare EGT probe reading against a borescope-observed condition). A rapidly fluctuating gauge often indicates a loose connector or intermittent sensor ground rather than an actual engine problem, while a slow drift over many flight hours is more likely a true sensor calibration or engine-condition change."},
      {"heading": "Instrument Calibration Verification", "body": "Engine instruments (tachometers, pressure gauges, temperature indicators) require periodic calibration verification against a known reference standard - a tachometer reading a few percent off can mask an engine actually operating outside its approved RPM range, with real consequences for engine life and performance. When replacing an engine instrument, verify the new unit's range and accuracy class matches the type-certificate data requirements, and perform an operational check comparing old versus new readings during the same engine run when possible, to catch a miscalibrated replacement before it enters service."}
    , {"heading": "Engine Instrument Sensor Types and Signal Conditioning", "body": "Engine instruments rely on various sensor technologies including thermocouples for temperature (EGT, oil temp), resistance temperature detectors (RTDs) for more precise temperature measurement, pressure transducers for oil and fuel pressure, and tachometer generators or Hall-effect sensors for RPM. Each sensor type has characteristic failure modes: thermocouple junction degradation causes gradual reading drift, RTD element cracking causes erratic jumps, and pressure transducer diaphragm fatigue causes slow zero-point drift. Signal conditioning circuits between the sensor and cockpit display can themselves fail, so isolating whether a suspect reading originates at the sensor, the wiring, or the display/conditioning unit requires systematic substitution testing rather than assuming the sensor is always at fault."},
    {"heading": "Digital Engine Instrument Data Bus Architecture", "body": "Modern turbine-powered aircraft transmit engine parameters over digital data buses such as ARINC 429, ARINC 664 (AFDX), or CAN rather than dedicated analog wires per gauge. An Engine Interface Unit (EIU) or Full Authority Digital Engine Control (FADEC) gathers raw sensor data, converts and validates it, then broadcasts labeled data words over the bus to the Engine Indicating and Crew Alerting System (EICAS) or Electronic Centralized Aircraft Monitor (ECAM) display computers. Because many parameters share a single physical bus, a wiring fault can cause multiple seemingly unrelated indications to fail simultaneously, which is a key troubleshooting clue distinguishing a bus/wiring fault from an individual sensor fault. Troubleshooting digital instrument faults requires bus analyzer tools or built-in maintenance pages that display raw label data, since a display anomaly may originate from the sensor, the interface unit's signal conditioning, the bus wiring, or the display computer itself."},
    {"heading": "Vibration Monitoring Instrumentation and Accelerometer Placement", "body": "Engine vibration monitoring systems use accelerometers mounted at specified locations on the engine case (often near the fan/N1 stage and the core/N2 stage on a turbofan) to sense vibration amplitude at specific frequencies correlating to rotor imbalance or bearing distress at each rotor's rotational speed. The cockpit vibration indication is typically filtered to display only the amplitude at the tracked rotor frequencies, ignoring broadband engine noise, so a rising vibration trend at a specific rotor's tracked frequency is a meaningful indicator of developing imbalance (such as from a damaged fan blade, ice ingestion, or bearing wear) rather than general engine roughness. Accelerometer mounting torque and orientation are critical since a loose or improperly oriented accelerometer produces erratic or falsely low readings; a vibration fault investigation should verify the accelerometer's physical installation and wiring integrity before concluding the engine itself has a vibration problem."}],
    "quiz": [ {"q": "What is the fundamental operating principle of a thermocouple used for exhaust gas temperature measurement?", "choices": ["It changes color at specific temperatures", "It generates a small voltage proportional to the temperature difference between its junctions", "It measures temperature by counting rotations", "It uses light reflection to sense temperature"], "answer": 1}, {"q": "What is a characteristic failure mode of a thermocouple sensor?", "choices": ["Instant total failure with no warning", "Gradual reading drift as the junction degrades", "Erratic RPM jumps", "Increased fuel consumption"], "answer": 1, "explain": "Thermocouple junctions tend to degrade gradually over time, causing slow drift in temperature readings rather than sudden failure."},
      {"q": "Why is comparing old versus new instrument readings during the same engine run valuable when replacing an engine gauge?", "choices": ["It is unnecessary busywork", "It helps catch a miscalibrated replacement instrument before it enters service", "It only matters for cosmetic reasons", "New instruments never need verification"], "answer": 1, "explain": "A side-by-side comparison during the same run helps verify the new instrument reads correctly, catching a miscalibration before it can mask a real engine problem later."},
      {"q": "A rapidly fluctuating (needle jumping) engine gauge reading is most often caused by:", "choices": ["A serious internal engine failure", "A loose connector or intermittent ground in the sensing circuit", "Normal operation", "Low oil pressure"], "answer": 1, "explain": "Erratic, rapid fluctuation is a classic symptom of a loose electrical connection or intermittent ground, not a true engine condition change."},
      {"q": "On many constant-speed-prop reciprocating engines, power setting is primarily indicated by:", "choices": ["Tachometer alone", "Manifold pressure (with RPM held constant by the governor)", "Oil temperature", "Fuel flow only"], "answer": 1, "explain": "With a constant-speed prop holding RPM steady, manifold pressure becomes the primary power-setting indicator."},
      {"q": "EGT/ITT is critical on turbine engines because it:", "choices": ["Indicates oil level", "Is the key limiting parameter protecting the hot section from damage", "Controls fuel color", "Measures airspeed"], "answer": 1, "explain": "Exceeding EGT/ITT limits accelerates hot-section wear/damage - it's the primary protective limit parameter on turbines."},
      {"q": "Engine trend monitoring is valuable because it:", "choices": ["Replaces the need for inspections entirely", "Reveals gradual degradation before it becomes an in-flight failure", "Only matters for brand-new engines", "Has no maintenance value"], "answer": 1, "explain": "Tracking parameters like EGT margin over time can catch developing problems (e.g., compressor wear) long before a failure occurs."},
      {"q": "A failed sensor on a glass engine display might:", "choices": ["Always show an obvious blank/error", "Show an erroneous but plausible-looking reading", "Shut down the engine automatically", "Have no possible failure mode"], "answer": 1, "explain": "Sensor failures can produce misleading in-range-looking readings - cross-checking against other engine parameters is a key habit."},
      {"q": "Torque indication is most associated with which engine type?", "choices": ["Piston engines", "Turboprop engines", "Ramjets only", "Electric motors"], "answer": 1, "explain": "Turboprop engines commonly use a torque gauge as the primary power-output indicator, since propeller thrust relates directly to shaft torque."},
    {"q": "Several apparently unrelated engine parameters on an EICAS display all fail or freeze at the same moment. What does this pattern most strongly suggest?", "choices": ["Each affected sensor has failed independently and coincidentally", "A shared digital data bus or interface unit fault, since multiple parameters are carried on the same bus", "A software update is required", "The display computer's backlight has failed"], "answer": 1},
    {"q": "Why is a rising vibration indication at a specific tracked rotor frequency considered more diagnostically meaningful than general engine noise?", "choices": ["Tracked frequency vibration has no diagnostic value", "It correlates specifically to that rotor's imbalance or bearing distress, filtering out unrelated broadband engine noise", "Vibration monitoring only measures cockpit noise levels, not engine condition", "All vibration frequencies indicate the same type of fault"], "answer": 1}
    ]
  },
  {
    "id": "welding_fabrication", "title": "Welding & Metal Fabrication", "track": "general", "icon": "&#x1F527;",
    "sections": [
      {"heading": "Aircraft Welding Processes", "body": "<b>Oxy-fuel (gas) welding</b> - traditional for steel tube structures, gives a wide heat-affected zone. <b>TIG (GTAW)</b> - precise, clean welds, standard for aluminum and stainless/steel repairs on certified aircraft today; uses inert shielding gas (argon) to prevent oxidation."},
      {"heading": "Welder & Weldment Approval", "body": "Aircraft welding on certificated aircraft structure generally requires an <b>FAA-approved welding process</b> and, for repairs, reference to approved data (AC 43.13-1B or the aircraft's SRM). Welder qualification/certification may be required by the operator/repair station even beyond A&P privileges for critical structure."},
      {"heading": "Base Metals & Filler Selection", "body": "4130 chromoly steel tube structures use matching or compatible filler rod. Aluminum structures (less common to weld vs rivet) need alloy-matched filler and careful heat control to avoid warping thin sheet. Never weld high-strength heat-treated parts without engineering approval - welding heat can destroy the temper."},
      {"heading": "Post-Weld Inspection & Treatment", "body": "Visual inspection for uniform bead, no undercut/porosity/cracks. Dye penetrant or X-ray for critical structural welds. <b>Stress relieving/normalizing</b> may be required after welding on hardened steel. Corrosion-proof (paint/primer) promptly after any weld repair on steel."},
      {"heading": "Weld Inspection and Common Defects", "body": "After welding an aircraft component, inspect for undercut (a groove melted into base metal at the weld toe, reducing thickness), porosity (gas bubbles trapped in the weld, seen as small holes on the surface or via X-ray), and incomplete fusion (weld metal didn't properly bond to base metal). A dye-penetrant check after welding helps reveal surface cracking that visual inspection alone can miss. Any structural weld repair must be performed per approved data with the correct filler rod and post-weld stress relief where specified - welding is not acceptable on many primary structure components without specific engineering approval."},
      {"heading": "Post-Weld Heat Treatment and Stress Relief", "body": "Welding introduces localized heating and cooling that creates residual stresses in the surrounding material - certain structural steel repairs require post-weld stress relief (controlled reheating and slow cooling) per the approved data to restore ductility and reduce the risk of cracking under subsequent service loads. Skipping specified stress relief on a repair that calls for it can leave a technically sound-looking weld with hidden residual stress that leads to premature fatigue cracking, often at the weld toe where stress concentration is highest."}
    , {"heading": "Weld Joint Design for Aircraft Structural Applications", "body": "Aircraft structural weld joint design favors continuous fillet or butt welds with smooth transitions rather than sharp corners, since stress concentrates at geometric discontinuities and can initiate fatigue cracking at joints that are otherwise structurally adequate under static load. Joint fit-up tolerances (gap width, alignment) must be maintained within the specification before welding begins, since excessive gap width requires additional filler material that can increase distortion and residual stress in the completed weld. Fillet weld size is specified by leg length or throat dimension appropriate to the loads the joint will carry, and undersized fillet welds are a common defect that may not be visually obvious but significantly reduce the joint's load-carrying capacity compared to design intent."},
    {"heading": "TIG vs. Gas Welding Selection for Aircraft Tube Structures", "body": "Gas Tungsten Arc Welding (TIG/GTAW) has largely replaced oxy-acetylene gas welding for aircraft steel tube structures because TIG provides a more concentrated, controllable heat source with an inert shielding gas that protects the weld puddle from atmospheric contamination, resulting in a narrower heat-affected zone, less distortion, and generally superior, more consistent weld quality, particularly on thin-wall chromoly tubing common in fuselage trusses and engine mounts. Gas welding remains an approved process for some applications and repairs where original type design used it, and some repair stations retain gas welding capability for specific legacy repairs, but new fabrication and most repairs on modern aircraft structures are performed with TIG per the applicable repair specification. Selection between the two processes for a given repair is not a matter of technician preference; it must follow the approved data (type certificate data, SRM, or engineering approval) governing that specific structure and repair."}],
    "quiz": [ {"q": "Why is smooth weld toe transition (where the weld meets base metal) particularly important in fatigue-critical joint locations?", "choices": ["It only affects the weld's cosmetic appearance", "Fatigue cracks preferentially initiate at abrupt profile changes acting as stress risers, so smooth transitions reduce this risk", "Weld toe geometry has no effect on structural performance", "Smooth transitions are only required for non-structural welds"], "answer": 1}, {"q": "Why do aircraft structural weld joints favor smooth transitions over sharp corners?", "choices": ["Sharp corners look unprofessional only", "Stress concentrates at geometric discontinuities and can initiate fatigue cracking", "Smooth transitions use less filler material", "Sharp corners are always stronger"], "answer": 1, "explain": "Sharp geometric discontinuities concentrate stress, which can initiate fatigue cracks at joints that would otherwise be structurally adequate under static loading."},
      {"q": "Why might a structural welded steel repair require post-weld stress relief even if the weld looks sound?", "choices": ["Stress relief is purely cosmetic", "Welding introduces residual stresses that can cause premature fatigue cracking if not relieved as specified", "It is never actually required", "It only affects paint adhesion"], "answer": 1, "explain": "Residual stress from welding can lead to premature cracking under service loads; stress relief restores ductility and reduces this risk even when the weld appears visually sound."},
      {"q": "Porosity in a weld appears as:", "choices": ["Extra weld strength", "Small gas-bubble holes trapped in the weld metal", "A discoloration only", "Correct penetration"], "answer": 1, "explain": "Porosity is trapped gas forming small voids/holes in the weld, which weakens it and is checked for visually and via X-ray."},
      {"q": "TIG welding is preferred over oxy-fuel for many modern aircraft repairs because it:", "choices": ["Is always cheaper", "Gives cleaner, more precise welds with inert-gas shielding", "Requires no skill", "Works only on aluminum"], "answer": 1, "explain": "TIG (GTAW) produces precise, clean welds using argon shielding gas, making it the standard for both steel and aluminum aircraft repairs today."},
      {"q": "Structural aircraft welding repairs must be performed using:", "choices": ["Any convenient method", "An FAA-approved process referencing approved data (AC 43.13-1B/SRM)", "Only oxy-fuel welding", "Whatever the mechanic prefers"], "answer": 1, "explain": "Welding on certificated structure must follow FAA-approved processes and approved repair data - it's not left to personal preference."},
      {"q": "Welding heat-treated high-strength steel parts without engineering approval risks:", "choices": ["No effect at all", "Destroying the part's temper/heat treatment and its strength", "Improving strength", "Only cosmetic discoloration"], "answer": 1, "explain": "Welding heat can undo heat-treatment (temper), significantly weakening a high-strength part unless properly re-treated per engineering data."},
      {"q": "After welding on a hardened steel structural part, you may need to:", "choices": ["Do nothing further", "Perform stress relieving/normalizing per approved data", "Paint immediately with no other treatment", "Sand only"], "answer": 1, "explain": "Stress relieving or normalizing restores appropriate material properties after the heat and stress of welding on hardened steel."},
      {"q": "Post-weld inspection of a critical structural weld often includes:", "choices": ["Visual only, never anything else", "Dye penetrant or X-ray (radiographic) inspection", "Weighing the part", "Nothing - welds are self-verifying"], "answer": 1, "explain": "Critical welds are commonly inspected with dye penetrant or radiography to detect cracks, porosity, or incomplete fusion not visible to the eye."},
    {"q": "Why has TIG welding largely replaced oxy-acetylene gas welding for aircraft steel tube structure fabrication?", "choices": ["TIG welding is always cheaper and faster regardless of quality", "TIG provides a more concentrated, controllable heat source with inert gas shielding, resulting in less distortion and more consistent weld quality", "Gas welding is no longer an approved process under any circumstances", "There is no meaningful quality difference between the two processes"], "answer": 1}
    ]
  }
]

EXT5_FLASHCARDS = [
  {"front":"Four Forces of Flight","back":"Lift, Weight, Thrust, Drag - balanced in steady level flight"},
  {"front":"Critical Angle of Attack","back":"AOA beyond which the wing stalls, regardless of airspeed"},
  {"front":"L/D Max","back":"Speed of lowest total drag - best glide/range speed"},
  {"front":"Load Factor & Stall Speed","back":"Stall speed increases with the square root of load factor (G)"},
  {"front":"Cabin Altitude","back":"Equivalent pressure altitude maintained inside a pressurized cabin"},
  {"front":"Pressure Relief Valve (cabin)","back":"Protects the fuselage from overpressurization damage"},
  {"front":"Oxygen + Hydrocarbon Hazard","back":"High-pressure O2 with oil/grease creates an explosion risk - use only O2-approved lubricants"},
  {"front":"Fuel Control Unit (FCU)","back":"Schedules turbine engine fuel flow for power, altitude, temperature"},
  {"front":"FADEC","back":"Full Authority Digital Engine Control - automated fuel scheduling and engine limit protection"},
  {"front":"Igniter Plug (turbine)","back":"High-energy plug used mainly for start and adverse-weather continuous ignition"},
  {"front":"Hot Start (turbine)","back":"EGT exceeds limit during start sequence"},
  {"front":"N1/N2","back":"Fan/compressor and turbine spool speeds, shown as % of max"},
  {"front":"Engine Trend Monitoring","back":"Tracking EGT/oil/fuel-flow/vibration over time to catch degradation before failure"},
  {"front":"TIG Welding (GTAW)","back":"Precise inert-gas-shielded welding process standard for modern aircraft repairs"},
  {"front":"Welding Approved Data","back":"Structural aircraft welds must follow FAA-approved processes referencing AC 43.13-1B/SRM"},
  {"front":"Stress Relieving","back":"Post-weld heat treatment restoring proper material properties in hardened steel"}
]

EXT5_GLOSSARY = [
  {"term":"Angle of Attack (AOA)","def":"Angle between the wing chord line and relative wind"},
  {"term":"Cabin Altitude","def":"Equivalent pressure altitude maintained inside a pressurized cabin"},
  {"term":"Critical AOA","def":"Angle of attack beyond which the wing stalls"},
  {"term":"EGT Margin","def":"Difference between current and limit EGT, tracked for engine health trending"},
  {"term":"FADEC","def":"Full Authority Digital Engine Control"},
  {"term":"Fuel Control Unit (FCU)","def":"Meters turbine fuel flow per power/altitude/temperature"},
  {"term":"Ignition Exciter","def":"Provides high-energy pulses to turbine igniter plugs"},
  {"term":"Induced Drag","def":"Drag from lift generation/wingtip vortices, decreases with speed"},
  {"term":"L/D Max","def":"Speed giving lowest total drag - best glide/range"},
  {"term":"Load Factor","def":"Ratio of aerodynamic lift to aircraft weight (in Gs)"},
  {"term":"Parasite Drag","def":"Drag from form/skin friction/interference, increases with speed squared"},
  {"term":"Stress Relieving","def":"Post-weld heat treatment restoring material properties"},
  {"term":"TIG Welding","def":"Inert-gas-shielded precision welding process (GTAW)"},
  {"term":"N1 / N2","def":"Turbine spool speeds shown as percent of maximum"}
]
